/**
 * Page sections: authored content where it exists, otherwise the composition generated by
 * scripts/compose-pages.ts. Read from disk (server-only, at build time) rather than imported, so the
 * 2 MB file is never typed as a literal or bundled.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { ContentSection } from "@/types/content";
import { getAuthoredContent } from "@/lib/content/authored";

let composed: Record<string, { recipe: string; sections: ContentSection[] }> | null = null;

function loadComposed() {
  composed ??= JSON.parse(readFileSync(join(process.cwd(), "content/generated/page-sections.json"), "utf8")).pages;
  return composed!;
}

export function getPageSections(page: number): { sections: ContentSection[]; source: "authored" | "composed" } {
  const authored = getAuthoredContent(page);
  if (authored) return { sections: authored.sections, source: "authored" };
  const entry = loadComposed()[String(page)];
  if (!entry) throw new Error(`No composed sections for PDF page ${page}; run npm run pages:compose`);
  return { sections: entry.sections, source: "composed" };
}
