import {
  Archive,
  ArchiveRestore,
  AtSign,
  BadgeCheck,
  BookOpen,
  Braces,
  Briefcase,
  Building2,
  CalendarDays,
  Camera,
  ChartColumn,
  CircleCheck,
  CircleHelp,
  Clock,
  Cloud,
  CodeXml,
  Compass,
  Copy,
  Database,
  Download,
  Eye,
  FileText,
  Film,
  Filter,
  Flag,
  Folder,
  Gauge,
  Globe,
  GraduationCap,
  Heart,
  History,
  Image,
  KeyRound,
  Layers,
  Library,
  Lock,
  Map,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  Music,
  Network,
  Newspaper,
  Palette,
  Plug,
  RefreshCw,
  ScanLine,
  ScrollText,
  Search,
  Server,
  Shield,
  Sparkles,
  Store,
  Tag,
  Trash2,
  TrendingUp,
  Type,
  Upload,
  User,
  Users,
  Video,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { TopicIcon } from "@/types/content";

/** Authored content names icons semantically; this is the only place they become glyphs. */
export const TOPIC_ICON: Record<TopicIcon, LucideIcon> = {
  search: Search,
  filter: Filter,
  tag: Tag,
  sparkles: Sparkles,
  scan: ScanLine,
  eye: Eye,
  palette: Palette,
  text: Type,
  copy: Copy,
  folder: Folder,
  layers: Layers,
  collection: Library,
  database: Database,
  upload: Upload,
  download: Download,
  refresh: RefreshCw,
  clock: Clock,
  history: History,
  archive: Archive,
  trash: Trash2,
  restore: ArchiveRestore,
  message: MessageSquare,
  thread: MessagesSquare,
  mention: AtSign,
  video: Video,
  image: Image,
  document: FileText,
  audio: Music,
  check: CircleCheck,
  approval: BadgeCheck,
  flag: Flag,
  users: Users,
  user: User,
  building: Building2,
  globe: Globe,
  lock: Lock,
  key: KeyRound,
  shield: Shield,
  audit: ScrollText,
  chart: ChartColumn,
  trend: TrendingUp,
  gauge: Gauge,
  calendar: CalendarDays,
  code: CodeXml,
  api: Braces,
  webhook: Webhook,
  plug: Plug,
  workflow: Workflow,
  server: Server,
  cloud: Cloud,
  network: Network,
  zap: Zap,
  map: Map,
  compass: Compass,
  book: BookOpen,
  help: CircleHelp,
  briefcase: Briefcase,
  megaphone: Megaphone,
  film: Film,
  camera: Camera,
  news: Newspaper,
  graduation: GraduationCap,
  heart: Heart,
  store: Store,
};
