import { readFileSync } from "node:fs";
import type { NextConfig } from "next";
import type { Inventory } from "./types/content.ts";

const inventory: Inventory = JSON.parse(readFileSync("./content/generated/inventory.json", "utf8"));

/*
 * Environment (see .env.example):
 *   SITE_ENV=production        indexing, production robots and HSTS; anything else is a closed preview
 *   NEXT_PUBLIC_SITE_URL       canonical origin; required for production builds (no fallback domain)
 */
const IS_PRODUCTION = process.env.SITE_ENV === "production";
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL;
if (IS_PRODUCTION && !SITE_URL) {
  throw new Error("SITE_ENV=production requires NEXT_PUBLIC_SITE_URL (the real production origin, e.g. https://…)");
}
const HTTPS_ORIGIN = !!SITE_URL?.startsWith("https://");
const DEVELOPMENT = process.env.NODE_ENV === "development";

/**
 * Content Security Policy. Next.js inlines its hydration scripts and styles on statically generated
 * pages, which cannot carry per-request nonces, so scripts and styles allow 'unsafe-inline' — but
 * only from this origin: no third-party scripts, frames, objects or form targets. Adding analytics or
 * any external embed requires extending this policy (docs/architecture/17-production-configuration.md).
 */
const contentSecurityPolicy = [
  "default-src 'self'",
  `script-src 'self' 'unsafe-inline'${DEVELOPMENT ? " 'unsafe-eval'" : ""}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  `connect-src 'self'${DEVELOPMENT ? " ws: wss:" : ""}`,
  "media-src 'self'",
  "object-src 'none'",
  "frame-src 'none'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "manifest-src 'self'",
  "worker-src 'self' blob:",
  ...(IS_PRODUCTION && HTTPS_ORIGIN ? ["upgrade-insecure-requests"] : []),
].join("; ");

const securityHeaders = [
  { key: "Content-Security-Policy", value: contentSecurityPolicy },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=(), payment=(), usb=()" },
  { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
  // HSTS only where the production origin is HTTPS. No includeSubDomains or preload until every
  // subdomain (including a future app.getsibu.com) is confirmed HTTPS-only.
  ...(IS_PRODUCTION && HTTPS_ORIGIN ? [{ key: "Strict-Transport-Security", value: "max-age=31536000" }] : []),
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  productionBrowserSourceMaps: false,
  // Clean URLs without trailing slashes; see docs/architecture/05-url-system.md.
  trailingSlash: false,
  // Every optimised image is served as WebP (the source files in public/ are WebP too); icon files and
  // the social card stay PNG because app icons and link-preview crawlers need it.
  images: {
    formats: ["image/webp"],
  },
  async headers() {
    return [{ source: "/:path*", headers: securityHeaders }];
  },
  async redirects() {
    // Merged PDF duplicates, held pages and supporting aliases. Generated by
    // scripts/build-inventory.ts so the list can never drift from the route matrix.
    return inventory.redirects;
  },
};

export default nextConfig;
