/**
 * GetSibu content model.
 *
 * Three layers, each with one owner:
 *
 * 1. Source      — `content/source/pdf-pages.json`. Verbatim extraction of Getsibu.pdf.
 *                  Generated by `scripts/extract-pdf-source.ts`. Never hand-edited.
 * 2. Architecture — `content/architecture/*.ts`. Hand-curated decisions: sections, URL rules,
 *                  page types, clusters, navigation, claims register.
 * 3. Inventory   — `content/generated/inventory.json`. Source × architecture, generated by
 *                  `scripts/build-inventory.ts`. Every route, SEO field and link is resolved here.
 *
 * Authored page bodies (Prompt 2+) live in `content/pages/**` as `PageContent` and are merged
 * onto the inventory entry at render time. They never redefine slug, title or SEO identity.
 *
 * All architecture modules may only use `import type` from this file so that Node's
 * type stripping can execute the build scripts without a compiler.
 */

/* ------------------------------------------------------------------------------------------ */
/* Source layer                                                                                */
/* ------------------------------------------------------------------------------------------ */

export interface PdfGroup {
  /** e.g. "11-30" */
  range: string;
  start: number;
  end: number;
  /** Heading exactly as written in the PDF, or a descriptive label when the PDF has none. */
  label: string;
  /** False for pages 1-10, which appear before the first group heading. */
  headingInSource: boolean;
}

export interface SourcePage {
  /** The page number as written in the PDF (1-400). Stable identity for every page. */
  number: number;
  /** Title exactly as written in the PDF. */
  sourceTitle: string;
  /** Title with typographic normalisation only ("--" → "—"). */
  title: string;
  /** Body paragraph exactly as written, line breaks joined. */
  text: string;
  group: PdfGroup;
}

/* ------------------------------------------------------------------------------------------ */
/* Provenance                                                                                  */
/* ------------------------------------------------------------------------------------------ */

/**
 * Every authored fact must point at where it came from. `editorial` is only for connective,
 * claim-free copy (headings like "Related capabilities", transitions, instructions).
 */
export type SourceRef =
  | { kind: "pdf"; page: number }
  | { kind: "site"; url: string; retrieved: string }
  | { kind: "editorial"; note?: string };

/* ------------------------------------------------------------------------------------------ */
/* Architecture layer                                                                          */
/* ------------------------------------------------------------------------------------------ */

export type SectionId =
  | "home"
  | "platform"
  | "features"
  | "storage"
  | "permissions"
  | "analytics"
  | "use-cases"
  | "integrations"
  | "developers"
  | "migration"
  | "architecture"
  | "security"
  | "pricing"
  | "business-value"
  | "resources"
  | "faq"
  | "get-started";

export type CategoryId =
  | "home"
  | "platform"
  | "search-discovery"
  | "ai"
  | "collaboration"
  | "asset-management"
  | "storage-ingestion"
  | "permissions-multi-tenancy"
  | "analytics"
  | "use-cases"
  | "integrations"
  | "developers"
  | "migration"
  | "architecture-performance"
  | "security-compliance"
  | "pricing-plans"
  | "business-value"
  | "resources"
  | "faq"
  | "conversion";

export type PageTypeId =
  | "home"
  | "platform"
  | "feature"
  | "ai-feature"
  | "workflow"
  | "storage"
  | "integration"
  | "access-security"
  | "analytics"
  | "developer"
  | "migration"
  | "architecture"
  | "use-case"
  | "pricing"
  | "business-value"
  | "resource"
  | "faq"
  | "conversion"
  | "section-index";

export type SearchIntent = "navigational" | "commercial" | "informational" | "transactional";

/**
 * Groups shown in global search results. They follow the PDF hierarchy: each is a category label (the
 * PDF group a page belongs to, as recorded in content/architecture/sections.ts), ordered by PDF page number,
 * so a result is labelled with the same group as its breadcrumb and hub.
 */
export type SearchGroup =
  | "Platform"
  | "Search & Discovery"
  | "AI"
  | "Collaboration"
  | "Versioning & Asset Management"
  | "Storage & Ingestion"
  | "Permissions & Multi-Tenancy"
  | "Analytics"
  | "Use Cases"
  | "Integrations"
  | "API & Developers"
  | "Migration"
  | "Architecture & Performance"
  | "Security & Compliance"
  | "Pricing & Plans"
  | "Business Value"
  | "Resources"
  | "FAQs"
  | "Get Started";

export interface SectionDef {
  id: SectionId;
  /** URL root, e.g. "/features". Home is "/". */
  basePath: string;
  label: string;
  /**
   * PDF page that *is* the section overview and therefore owns `basePath`.
   * When absent, `basePath` is a generated index page (see `IndexPageDef`).
   */
  rootPage?: number;
  categories: CategoryId[];
}

export interface CategoryDef {
  id: CategoryId;
  section: SectionId;
  label: string;
  /** Short label for navigation columns and breadcrumbs. */
  shortLabel: string;
  /** PDF group ranges whose pages default into this category. */
  pdfRanges: Array<[number, number]>;
  /** Hub URL for the category. Equals the section basePath for single-category sections. */
  hubPath: string;
  pageType: PageTypeId;
  searchGroup: SearchGroup;
  /** Visual direction for the category, see docs/architecture/08-visual-and-image-strategy.md */
  visual: VisualDirection;
}

export interface IndexPageDef {
  id: string;
  path: string;
  section: SectionId;
  category?: CategoryId;
  title: string;
  h1: string;
  /** Intro shown under the H1: verbatim PDF sentence(s), cited, or claim-free editorial copy. */
  lede: string;
  ledeSource: SourceRef[];
  /**
   * Meta description. Written from PDF terminology (cluster and page names) rather than copied
   * from a page paragraph, so it can never collide with a PDF page's own description.
   */
  description: string;
  /** Cluster ids rendered as sub-groups, in order. Pages not in any listed cluster fall into "More". */
  groupBy: string[];
  /** Canonical pages from other sections that belong on this index. */
  crossListings?: number[];
}

export interface TopicCluster {
  id: string;
  label: string;
  /** Pillar page other members point to for the shared topic. */
  primary: number;
  members: number[];
  /**
   * "high" means members' PDF paragraphs are near-identical. Content authors must write to the
   * angle recorded in `angles` so the pages do not duplicate each other.
   */
  overlapRisk: "low" | "medium" | "high";
  /** Per-page angle, derived from where the PDF places the page. */
  angles?: Record<number, string>;
}

export type VisualMedium =
  | "product-ui"
  | "diagram"
  | "photography"
  | "data-visual"
  | "code-concept"
  | "typographic";

export interface VisualDirection {
  medium: VisualMedium[];
  concept: string;
  avoid: string[];
}

export type ClaimStatus =
  /** Present in the PDF; not found on the official website. */
  | "pdf-stated"
  /** The PDF itself hedges the claim ("stated positioning", "stated direction"). */
  | "pdf-hedged"
  /** Stated on the official website, with no conflict found. */
  | "site-stated"
  /** Stated on the official website, but the site contradicts itself or the product's own code does. */
  | "conflicting"
  /** Confirmed in writing by GetSibu. The only status that unlocks high-risk claims. */
  | "client-confirmed";

export interface Claim {
  id: string;
  statement: string;
  status: ClaimStatus;
  /**
   * "high": numbers, limits, certifications, compliance, named third parties, prices, security
   * mechanisms — publishable only when `client-confirmed`.
   * "standard": descriptive capability claims — publishable when PDF- or site-stated.
   */
  risk: "high" | "standard";
  /** PDF pages that state the claim. Empty for claims that appear only on the official site. */
  pdfPages: number[];
  /** Exact wording on the official site, when present. */
  siteWording?: string[];
  conflicts?: string[];
  evidence?: SourceRef[];
  /** Case-insensitive, word-bounded phrases the validator uses to detect the claim in copy. */
  detect: string[];
  note?: string;
}

/* ------------------------------------------------------------------------------------------ */
/* Inventory layer (generated)                                                                 */
/* ------------------------------------------------------------------------------------------ */

export interface BreadcrumbItem {
  label: string;
  path: string;
}

export interface CtaRef {
  /** "global:<id>" resolves from `lib/site.ts`; "page:<n>" links to a PDF conversion page. */
  target: string;
  label: string;
  href: string;
}

export interface SeoData {
  /** <title>. Brand appended unless the title already contains "GetSibu". */
  title: string;
  h1: string;
  /** Drafted from the first source sentence(s); ≤ 160 chars. */
  description: string;
  canonicalPath: string;
  /** schema.org types emitted for the page. */
  schemaTypes: string[];
  robots: "index,follow" | "noindex,follow";
  sitemap: boolean;
}

export interface InventoryPage {
  /** PDF page number, also the stable id. */
  number: number;
  title: string;
  sourceTitle: string;
  sourceText: string;
  pdfGroup: PdfGroup;

  status: "canonical" | "merged";
  /** For merged pages: the canonical page number whose URL serves this topic. */
  mergedInto?: number;
  /** For canonical pages: PDF pages merged into this one, whose paragraphs are extra source material. */
  mergedSources: number[];

  section: SectionId;
  category: CategoryId;
  role: "home" | "section-root" | "leaf";
  slug: string;
  /** Canonical URL path (merged pages carry the canonical page's path). */
  path: string;
  /** Paths that 308-redirect to `path`. */
  aliases: string[];
  parentPath: string | null;
  breadcrumb: BreadcrumbItem[];

  pageType: PageTypeId;
  /** Section recipe variant chosen for layout rhythm; see content/architecture/page-types.ts. */
  recipe: string;

  primaryTopic: string;
  intent: SearchIntent;
  /** What the page must accomplish for the reader. */
  purpose: string;
  /** The first sentence of the source paragraph — the page's core statement. */
  keyStatement: string;

  clusters: string[];
  /** Ordered, de-duplicated related pages (canonical numbers only). */
  related: number[];
  /** Concepts named in the source paragraph that have their own page. */
  mentions: number[];
  relatedFeatures: number[];
  relatedResources: number[];
  relatedFaqs: number[];
  relatedUseCases: number[];
  /** Pages listed under this page (section roots only). */
  children: number[];
  /** The same pages grouped by topic cluster, in display order (section roots only). */
  childGroups: Array<{ clusterId: string | null; label: string; pages: number[] }>;
  previous: number | null;
  next: number | null;

  cta: {
    primary: CtaRef;
    contextual: CtaRef | null;
  };

  seo: SeoData;
  searchGroup: SearchGroup;
  visual: VisualDirection & { subject: string };

  /** Claim ids detected in the source paragraph. */
  claims: string[];
  /** True when any detected claim is not publishable yet (see `isPublishable` in claims.ts). */
  needsVerification: boolean;
  /**
   * For pages that need verification: the publishable page that frames them (hero lede, meta
   * description). See content/architecture/verified-context.ts. Null for publishable pages.
   */
  contextPage: number | null;
  /**
   * published — no unconfirmed claims.
   * framed    — needs verification, but its title is safe: published with verified context.
   * held      — its title itself states an unconfirmed claim: not published anywhere; the URL
   *             redirects temporarily to the context page (content/architecture/verified-context.ts).
   */
  publication: "published" | "framed" | "held";
  /** Overlap notes the content author must respect. */
  angle: string | null;
}

/**
 * One row of the route matrix (content/generated/route-matrix.json, docs/route-matrix.csv): every URL
 * the site answers, with how it must behave. scripts/verify-build.ts checks the built site against it.
 *
 *   LIVE       canonical, published, indexable, in the sitemap and search
 *   SAFE-LIVE  published from verified material only; indexability set deliberately (framed pages,
 *              company pages, site search)
 *   HELD       an inventory page whose title states an unconfirmed claim: no page, navigation, sitemap
 *              or search entry; its URL redirects temporarily to verified context
 *   REDIRECT   an alias that publishes nothing (merged PDF duplicates, /about-us)
 */
export interface RouteMatrixRow {
  path: string;
  class: "LIVE" | "SAFE-LIVE" | "HELD" | "REDIRECT";
  kind: "home" | "page" | "hub" | "company" | "utility" | "held-page" | "merged-alias" | "supporting-alias";
  pdfPage: number | null;
  title: string;
  status: 200 | 307 | 308;
  destination: string | null;
  indexable: boolean;
  sitemap: boolean;
  search: boolean;
  navigation: boolean;
  /** Unpublishable claims behind a SAFE-LIVE or HELD row. */
  claims: string[];
  note: string;
}

export interface InventoryIndexPage extends IndexPageDef {
  seo: SeoData;
  breadcrumb: BreadcrumbItem[];
  groups: Array<{ clusterId: string | null; label: string; pages: number[] }>;
}

export interface Inventory {
  generatedAt: string;
  source: { file: string; pages: number };
  pages: InventoryPage[];
  indexes: InventoryIndexPage[];
  /** Permanent for merged duplicates; temporary while a page is held. */
  redirects: Array<{ source: string; destination: string; permanent: boolean }>;
}

/* ------------------------------------------------------------------------------------------ */
/* Authored content (Prompt 2+)                                                                */
/* ------------------------------------------------------------------------------------------ */

export interface MediaRef {
  /** Asset id in the media registry — each id may be used on one page only unless `shared`. */
  assetId: string;
  alt: string;
  /** Required when the visual is a product capture: which screen, supplied by whom. */
  provenance: SourceRef;
  aspect?: "16:9" | "4:3" | "3:2" | "1:1" | "4:5" | "21:9";
}

/**
 * Data-driven SVG figures (components/diagrams). A diagram draws facts from its section's sources;
 * it is never a mock-up of the product interface.
 */
export type DiagramId =
  | "library-search"
  | "search-signals"
  | "ai-review"
  | "timeline-review"
  | "version-record"
  | "folder-access"
  | "library-activity"
  | "tenant-boundaries"
  | "api-flow"
  | "ingest-pipeline"
  | "architecture-stack"
  | "migration-map"
  | "connector-flow"
  | "control-map"
  | "media-library";

/**
 * A diagram plus the part of it this page is about. `focus` is a diagram-specific key (for example
 * "ocr" on search-signals, "edge" on architecture-stack) that lights that part up, so pages sharing
 * a figure still show their own place in the system. `label` names an external tool (connector-flow).
 */
export interface VisualRef {
  diagram: DiagramId;
  focus?: string;
  label?: string;
}

/** A link to another page, always by PDF number; label defaults to the page title. */
/** Plain text, or text with inline links: each link wraps a phrase of the text and points at a page by PDF number. */
export type RichText = string | Array<string | { text: string; page: number }>;

export interface PageLinkRef {
  page: number;
  label?: string;
}

/**
 * Hero and CTA actions: the global CTAs from navigation.ts, a page by PDF number, or an inventory
 * route such as a hub (validated against the inventory).
 */
export type ActionRef =
  | { kind: "global"; cta: "primary" | "secondary" }
  | ({ kind: "page" } & PageLinkRef)
  | { kind: "route"; path: string; label: string };

/** An item in a set that may point at a page; `current` marks the page being viewed. */
interface Linked {
  page?: number;
  current?: boolean;
}

/**
 * Semantic icon names authored content may use. The presentation layer maps each name to a glyph, so
 * content never depends on an icon library. Icons decorate; the text beside them carries the meaning.
 */
export type TopicIcon =
  | "search"
  | "filter"
  | "tag"
  | "sparkles"
  | "scan"
  | "eye"
  | "palette"
  | "text"
  | "copy"
  | "folder"
  | "layers"
  | "collection"
  | "database"
  | "upload"
  | "download"
  | "refresh"
  | "clock"
  | "history"
  | "archive"
  | "trash"
  | "restore"
  | "message"
  | "thread"
  | "mention"
  | "video"
  | "image"
  | "document"
  | "audio"
  | "check"
  | "approval"
  | "flag"
  | "users"
  | "user"
  | "building"
  | "globe"
  | "lock"
  | "key"
  | "shield"
  | "audit"
  | "chart"
  | "trend"
  | "gauge"
  | "calendar"
  | "code"
  | "api"
  | "webhook"
  | "plug"
  | "workflow"
  | "server"
  | "cloud"
  | "network"
  | "zap"
  | "map"
  | "compass"
  | "book"
  | "help"
  | "briefcase"
  | "megaphone"
  | "film"
  | "camera"
  | "news"
  | "graduation"
  | "heart"
  | "store";

interface SectionBase {
  /** Stable id used for anchors and analytics. */
  id: string;
  sources: SourceRef[];
  /** Short label above the heading. Must name something true (a category, a step), not decorate. */
  eyebrow?: string;
  /** One or two sentences under the heading. */
  intro?: string;
  /** Visual rhythm hint for spacing: dense sections get tighter padding. */
  density?: "dense" | "open";
  /** Colour surface for the section band. */
  surface?: "default" | "muted" | "inverse";
}

export type ContentSection =
  | (SectionBase & {
      kind: "hero";
      /** Omitted when the page's source paragraph states a claim that is not publishable yet. */
      lede?: string;
      /** When the lede is another page's statement (pages that need verification): that page. */
      context?: PageLinkRef;
      media?: MediaRef;
      diagram?: DiagramId;
      visual?: VisualRef;
      layout: "split" | "centered" | "statement";
      actions?: ActionRef[];
      /** Up to three short checked items under the actions (homepage). Visible claims: sourced, never numeric. */
      points?: string[];
    })
  | (SectionBase & { kind: "definition"; term: string; answer: RichText; detail?: RichText })
  /**
   * The topic explained: 2–4 paragraphs, the key concepts as chips, an optional "in practice" callout
   * and an at-a-glance card. Glance facts and tags are visible claims: sourced, never numeric or priced
   * unless the claim is confirmed.
   */
  | (SectionBase & {
      kind: "overview";
      heading: string;
      body: RichText[];
      keyPoints: { heading: string; items: string[] };
      highlight?: { heading: string; body: RichText; tags?: string[] };
      glance?: { heading: string; facts: Array<{ label: string; value: string; page?: number }>; actions?: ActionRef[] };
    })
  /** Two to five views of one topic (by team, by asset type, by stage). Every panel is in the HTML. */
  | (SectionBase & {
      kind: "tabs";
      heading: string;
      tabs: Array<{ label: string; heading: string; body: RichText[]; points?: string[]; icon?: TopicIcon; visual?: VisualRef; link?: PageLinkRef }>;
    })
  /** Expandable deep dives: a one-line summary always visible, the detail on demand. */
  | (SectionBase & {
      kind: "accordion";
      heading: string;
      items: Array<{ heading: string; summary: string; body: RichText[]; points?: string[]; icon?: TopicIcon; page?: number }>;
    })
  /** An illustrative, unnamed team working through the topic. Every GetSibu action in it is sourced. */
  | (SectionBase & {
      kind: "scenario";
      heading: string;
      team: string;
      situation: RichText;
      steps: Array<{ heading: string; body: RichText }>;
      outcome: RichText;
      link?: PageLinkRef;
    })
  | (SectionBase & {
      kind: "editorial";
      heading: string;
      /** Plain paragraphs, or a lead-in (usually a page title) followed by that page's statement. */
      body: Array<string | ({ lead: string; text: string } & Linked)>;
    })
  | (SectionBase & {
      kind: "split";
      heading: string;
      body: string[];
      media?: MediaRef;
      diagram?: DiagramId;
      visual?: VisualRef;
      mediaSide: "start" | "end";
      points?: string[];
      links?: PageLinkRef[];
    })
  | (SectionBase & {
      kind: "story";
      heading: string;
      visual: VisualRef;
      steps: Array<{ heading: string; body: string; media?: MediaRef; focus?: string } & Linked>;
    })
  | (SectionBase & { kind: "workflow"; heading: string; stages: Array<{ label: string; body: string } & Linked> })
  | (SectionBase & { kind: "process"; heading: string; steps: Array<{ heading: string; body: string; icon?: TopicIcon } & Linked> })
  | (SectionBase & { kind: "timeline"; heading: string; items: Array<{ label: string; body: string } & Linked> })
  | (SectionBase & {
      kind: "capabilities";
      heading: string;
      items: Array<{ heading: string; body: string; icon?: TopicIcon; points?: string[] } & Linked>;
    })
  | (SectionBase & {
      kind: "category-explorer";
      heading: string;
      categories: Array<{ category: CategoryId; summary: string; pages: number[]; diagram: DiagramId }>;
    })
  | (SectionBase & {
      kind: "comparison";
      heading: string;
      columns: [string, string];
      rows: Array<[string, string, string]>;
      /** Which column is GetSibu's, so it can be emphasised. */
      emphasis?: 0 | 1;
    })
  | (SectionBase & {
      kind: "before-after";
      heading: string;
      beforeLabel: string;
      afterLabel: string;
      before: string[];
      after: string[];
      link?: PageLinkRef;
    })
  | (SectionBase & { kind: "statement"; text: string; attribution?: never; link?: PageLinkRef })
  | (SectionBase & { kind: "media"; media?: MediaRef; visual?: VisualRef; caption?: string })
  | (SectionBase & {
      kind: "alternating";
      heading: string;
      rows: Array<{ heading: string; body: string; media?: MediaRef; visual?: VisualRef } & Linked>;
    })
  | (SectionBase & { kind: "layers"; heading: string; layers: Array<{ label: string; body: string } & Linked> })
  | (SectionBase & {
      kind: "matrix";
      heading: string;
      columns: string[];
      rows: Array<{ label: string; cells: string[] } & Linked>;
    })
  | (SectionBase & { kind: "plans"; heading: string; planPages: number[] })
  | (SectionBase & {
      kind: "checklist";
      heading: string;
      /** "chips" renders short labels as a compact grid of pills. */
      variant?: "list" | "chips";
      /** A label, or a page whose inventory title is shown (titles of pages that need verification stay out of copy). */
      items: Array<string | ({ label: string } & Linked) | ({ label?: undefined; page: number } & Linked)>;
    })
  | (SectionBase & { kind: "event-list"; heading: string; events: Array<{ name: string; body: string } & Linked> })
  | (SectionBase & { kind: "faq"; heading: string; items: Array<{ question: string; answer: RichText; page?: number }> })
  /** "compact" is a short strip of small link cards (at most six), not a directory. */
  | (SectionBase & { kind: "related"; heading: string; pages: number[]; variant?: "index" | "cards" | "compact" })
  | (SectionBase & { kind: "cta"; heading: string; body?: string; conversionPage?: number; actions?: ActionRef[] });

export type SectionKind = ContentSection["kind"];

export interface PageContent {
  /** PDF page number this content belongs to. */
  page: number;
  /** Must equal the inventory recipe unless `recipeOverride` explains why. */
  recipeOverride?: { recipe: string; reason: string };
  sections: ContentSection[];
  /** Optional refinement of the drafted meta description. Title/H1/slug are not overridable here. */
  metaDescription?: string;
  lastReviewed: string;
}

/* ------------------------------------------------------------------------------------------ */
/* Image Inventory & Matrix layer                                                             */
/* ------------------------------------------------------------------------------------------ */

export interface ImageInventoryEntry {
  path: string;
  filename: string;
  page: string;
  topicNumber: number;
  topic: string;
  section: string;
  purpose: string;
  prompt: string;
  alt: string;
  dimensions: { width: number; height: number };
  format: "webp";
  uniquenessStatus: "unique";
  usedCount: 1;
  hash?: string;
  /** The source photo the image was cropped from (key in content/architecture/image-sources.ts). */
  source?: string;
}

export interface TopicImageMatrixRow {
  topicNumber: number;
  topic: string;
  url: string;
  publication: "published" | "framed" | "held";
  category: CategoryId;
  heroImage: string;
  heroFilename: string;
  heroAlt: string;
  heroPurpose: string;
  sectionImages: Array<{
    section: string;
    path: string;
    filename: string;
    alt: string;
    purpose: string;
  }>;
  imageUniqueness: "verified-unique";
  contentImageRelevance: string;
  generationStatus: "generated" | "curated" | "pending";
  webpStatus: "valid-webp";
  qaStatus: "passed" | "pending";
}

export interface ImageInventoryAuditReport {
  totalAuditedPages: number;
  pagesWithHeroImages: number;
  uniqueHeroImages: number;
  totalUniqueImages: number;
  totalSectionImages: number;
  webpImages: number;
  missingAltText: number;
  duplicateUsages: number;
  contentImageMismatches: number;
  watermarkedImages: number;
  thirdPartyImages: number;
  imagesRequiringReplacement: number;
  brokenImages: number;
  /** Distinct source photos behind the images, and the most images cropped from one of them. */
  sourcePhotos?: number;
  maxSourceReuse?: number;
  /** Images whose source photo is not recorded or not reviewed in content/architecture/image-sources.ts. */
  unreviewedImages?: number;
  /** Images whose alt text does not name GetSibu, or (on a live page) the page's topic title. */
  altWithoutSiteOrTopic?: number;
  qaStatus: "passed" | "failed";
}

