/**
 * Icon vocabulary for the Sky9-style presentation (lucide, as on the reference). Icons are
 * decorative: every place that shows one also names the thing in text.
 */
import {
  Activity,
  Archive,
  ArrowRightLeft,
  BadgeCheck,
  BookOpen,
  Boxes,
  Building2,
  ChartColumn,
  ChartLine,
  CircleHelp,
  ClipboardCheck,
  Cloud,
  CloudUpload,
  CodeXml,
  Compass,
  Database,
  Eye,
  FileText,
  Film,
  FolderLock,
  FolderTree,
  Gauge,
  Globe,
  GraduationCap,
  History,
  House,
  Image,
  KeyRound,
  Layers,
  LayoutGrid,
  Library,
  Lightbulb,
  ListChecks,
  LockKeyhole,
  type LucideIcon,
  Megaphone,
  MessagesSquare,
  Music,
  Network,
  Plug,
  Rocket,
  Route,
  ScanSearch,
  ScanText,
  Search,
  Server,
  Share2,
  ShieldCheck,
  Sparkles,
  Tags,
  Target,
  Upload,
  UserCheck,
  Users,
  Video,
  WandSparkles,
  Webhook,
  Workflow,
  Zap,
} from "lucide-react";
import type { CategoryId, PageTypeId, SectionId } from "@/types/content";

export type { LucideIcon };

export const CATEGORY_ICON: Record<CategoryId, LucideIcon> = {
  home: House,
  platform: Layers,
  "search-discovery": Search,
  ai: WandSparkles,
  collaboration: MessagesSquare,
  "asset-management": History,
  "storage-ingestion": CloudUpload,
  "permissions-multi-tenancy": FolderLock,
  analytics: ChartColumn,
  "use-cases": Users,
  integrations: Plug,
  developers: CodeXml,
  migration: ArrowRightLeft,
  "architecture-performance": Server,
  "security-compliance": ShieldCheck,
  "pricing-plans": Target,
  "business-value": ChartLine,
  resources: BookOpen,
  faq: CircleHelp,
  conversion: Rocket,
};

export const SECTION_ICON: Record<SectionId, LucideIcon> = {
  home: House,
  platform: Layers,
  features: LayoutGrid,
  storage: CloudUpload,
  permissions: FolderLock,
  analytics: ChartColumn,
  "use-cases": Users,
  integrations: Plug,
  developers: CodeXml,
  migration: ArrowRightLeft,
  architecture: Server,
  security: ShieldCheck,
  pricing: Target,
  "business-value": ChartLine,
  resources: BookOpen,
  faq: CircleHelp,
  "get-started": Rocket,
};

export const PAGE_TYPE_ICON: Partial<Record<PageTypeId, LucideIcon>> = {
  "ai-feature": Sparkles,
  workflow: Workflow,
  storage: Upload,
  integration: Plug,
  "access-security": LockKeyhole,
  developer: Webhook,
  migration: Route,
  architecture: Network,
  "use-case": Building2,
  resource: GraduationCap,
  faq: CircleHelp,
  conversion: Rocket,
};

/**
 * A cycling set for step and card grids whose items have no category of their own. Chosen for
 * meaning where the label says so (see iconForLabel), otherwise in order.
 */
const CYCLE: LucideIcon[] = [Compass, Layers, Zap, ClipboardCheck, BadgeCheck, Boxes, Lightbulb, ListChecks];

const BY_WORD: Array<[RegExp, LucideIcon]> = [
  [/search|discover|find|query/i, Search],
  [/ocr|text inside|extract/i, ScanText],
  [/ai|tag|classif|detect|suggest|intellig/i, Sparkles],
  [/upload|ingest|import|connect|source/i, Upload],
  [/process|index/i, ScanSearch],
  [/preview|stream|view|watch/i, Eye],
  [/comment|feedback|review|mention|discuss|collaborat/i, MessagesSquare],
  [/approv|status|verif|record|audit|history/i, ClipboardCheck],
  [/version|replace|restore|revision/i, History],
  [/archive|lifecycle|expir|delet/i, Archive],
  [/permission|access|role|folder|private|admin|default-deny|security|secret|encrypt/i, LockKeyhole],
  [/tenant|client|agenc|isolat|white-label/i, Building2],
  [/team|user|contributor|people|individual|manager|editor/i, Users],
  [/analytic|report|metric|kpi|trend|activity|usage|dashboard/i, Activity],
  [/storage|cloud|library|central/i, Database],
  [/api|developer|webhook|sdk|integration|automat/i, Webhook],
  [/migrat|map|strategy|plan|implement/i, Route],
  [/cdn|edge|global|delivery/i, Globe],
  [/performance|speed|fast|scal/i, Gauge],
  [/video|footage|film/i, Video],
  [/image|photo/i, Image],
  [/document|pdf/i, FileText],
  [/audio/i, Music],
  [/organis|taxonom|collection|structure/i, FolderTree],
  [/share/i, Share2],
  [/brand|marketing|campaign/i, Megaphone],
  [/production|studio/i, Film],
  [/learn|education|what is|guide/i, GraduationCap],
  [/start|launch|get started/i, Rocket],
  [/key|auth|sign/i, KeyRound],
  [/cloud/i, Cloud],
  [/check|verified/i, UserCheck],
  [/library/i, Library],
];

export function iconForLabel(label: string, index = 0): LucideIcon {
  for (const [pattern, icon] of BY_WORD) if (pattern.test(label)) return icon;
  return CYCLE[index % CYCLE.length];
}
