/**
 * 135 · Digital Asset Import — /storage/digital-asset-import
 *
 * Angle (cluster: ingestion): multiple entry points as flexibility in building a library — what each route
 * is for, a library built route by route, and how to choose and own routes. Automated Asset Ingestion (121)
 * owns the overview of ingestion; each route has its own page.
 */
import type { PageContent } from "../../../types/content.ts";

const EXPLAINS = { kind: "editorial", note: "Explanation of how teams combine import routes; states no GetSibu capability beyond the cited pages." } as const;

const page: PageContent = {
  page: 135,
  lastReviewed: "2026-09-15",
  sections: [
    {
      kind: "hero",
      id: "hero",
      layout: "split",
      eyebrow: "Storage & Ingestion",
      lede: "Compare the routes by which assets can reach GetSibu, see how one team might combine them, and work through the questions that decide which route new material should take.",
      visual: { diagram: "ingest-pipeline", focus: "sources" },
      actions: [
        { kind: "global", cta: "primary" },
      ],
      sources: [{ kind: "pdf", page: 135 }],
    },
    {
      kind: "overview",
      id: "overview",
      heading: "More than one way in, and a reason for each",
      body: [
        "Digital assets can enter GetSibu through multiple sources, which gives teams flexibility in how they build their library. The route can follow the material, instead of every kind of material being forced through the same door.",
        "A creative library is fed by very different arrivals: an archive that already exists, work produced every week, deliveries from people outside the organisation and files generated by other software. A library with a single entry route makes some of these awkward, and awkward routes get bypassed. The file stays on a desktop, and the library gradually stops being complete.",
        "Flexibility is not the same as a free-for-all. Several routes into one library work well when each has a clear purpose and an owner, so people know which one to use and the same material does not arrive twice by different means.",
        [
          "When assets enter GetSibu, their available metadata is processed and they are prepared for search and organisation, which is the work of ",
          { text: "creative asset indexing", page: 21 },
          ".",
        ],
      ],
      keyPoints: {
        heading: "Key concepts",
        items: ["Multiple sources into one library", "A route matched to the material", "Archives, new work and deliveries", "A purpose and an owner per route", "Indexing once assets enter"],
      },
      glance: {
        heading: "Digital asset import in brief",
        facts: [
          { label: "Area", value: "Storage & Ingestion" },
          { label: "Enters through", value: "Multiple sources" },
          { label: "Gives teams", value: "Flexibility in building the library" },
          { label: "Ingestion overview", value: "Automated Asset Ingestion", page: 121 },
        ],
        actions: [{ kind: "route", path: "/storage", label: "More in Storage & Ingestion" }]
      },
      sources: [{ kind: "pdf", page: 135 }, { kind: "pdf", page: 21 }, { kind: "pdf", page: 121 }, EXPLAINS],
    },
    {
      kind: "matrix",
      id: "routes",
      eyebrow: "Compare the routes",
      heading: "Routes into the library and what each one is for",
      columns: ["Best suited to", "What sets it going", "Worth deciding first"],
      rows: [
        { label: "Drag and drop upload", page: 127, cells: ["Individual assets and small batches", "A person adding files they have chosen", "Who is allowed to add files"] },
        { label: "Watch folders", page: 128, cells: ["A location that keeps receiving new content", "Content newly added to the folder", "What the folder is for and what may go in it"] },
        { label: "Bulk asset import", page: 130, cells: ["Large existing libraries", "A planned import with a defined scope", "Whether folders are mirrored or remapped"] },
        { label: "Connected storage sources", page: 121, cells: ["Libraries in storage the team already uses", "Connecting that storage as a source", "Which locations deserve connecting"] },
        { label: "Asset upload API", page: 262, cells: ["Files produced by other applications", "An external application sending files", "Which systems should hand files over"] },
      ],
      sources: [{ kind: "pdf", page: 127 }, { kind: "pdf", page: 128 }, { kind: "pdf", page: 130 }, { kind: "pdf", page: 133 }, { kind: "pdf", page: 121 }, { kind: "pdf", page: 2 }, { kind: "pdf", page: 262 }, EXPLAINS],
    },
    {
      kind: "scenario",
      id: "scenario",
      eyebrow: "Practical use case",
      heading: "A library assembled one route at a time",
      team: "An in-house creative team",
      situation: "An in-house creative team at a consumer electronics company is moving from a patchwork of drives to a single library. It has a large archive, a busy product photography studio, regular agency deliveries and a product information system that generates packshots.",
      steps: [
        { heading: "Bring the archive across", body: ["The archive arrives through a bulk import, with the old folder structure ", { text: "mirrored during import", page: 133 }, " so long-serving staff can find their way around."] },
        { heading: "Give the studio a watched location", body: "Finished photography saved into a watched folder can enter the workflow automatically, so the studio does not need to run separate uploads." },
        { heading: "Let the system hand over packshots", body: ["Developers use the ", { text: "asset upload API", page: 262 }, " so the product information system can send its images into the library."] },
        { heading: "Keep deliveries moving", body: "Agency finals still arrive by email, and a coordinator adds them in small batches by drag and drop on the day they land." },
        { heading: "Write the routes down", body: "The library manager keeps a short note of which route carries which material and who owns it, so a new studio assistant knows to save into the watched folder rather than upload finished shots by hand." },
      ],
      outcome: "The library fills from every direction the team works in, and because each route has a stated purpose, people know how to add material without having to ask.",
      link: { page: 222, label: "GetSibu for In-House Creative Teams" },
      sources: [{ kind: "pdf", page: 130 }, { kind: "pdf", page: 133 }, { kind: "pdf", page: 128 }, { kind: "pdf", page: 262 }, { kind: "pdf", page: 127 }, { kind: "pdf", page: 222 }, { kind: "editorial", note: "Illustrative scenario; the team is hypothetical and unnamed." }],
    },
    {
      kind: "accordion",
      id: "choosing",
      eyebrow: "Decisions",
      heading: "Choosing an import route for new material",
      surface: "muted",
      items: [
        {
          heading: "How often does it arrive?",
          summary: "Frequency separates a one-off job from a continuing flow.",
          icon: "clock",
          body: [
            "Something that arrives once, however large, is a project with a beginning and an end. Something that arrives every day is a process, and processes are better served by routes that do not depend on a person remembering to act.",
          ],
        },
        {
          heading: "Who, or what, will add it?",
          summary: "A route that suits a producer is not necessarily one that suits a system.",
          icon: "users",
          body: [
            ["People need routes that fit their working day; software needs routes that developers can automate. ", { text: "Governance", page: 114 }, " defines who can upload and manage assets, which settles who may use a route in the first place."],
          ],
        },
        {
          heading: "What has to come with it?",
          summary: "Some material is valuable mainly for the information it carries.",
          icon: "tag",
          body: [
            ["An archive from a previous system may matter as much for its keywords and credits as for its files. That points to a planned import in which metadata such as creators and custom keywords ", { text: "can be preserved", page: 132 }, ", rather than file-by-file uploads that easily separate files from the records kept about them."],
          ],
        },
      ],
      sources: [{ kind: "pdf", page: 114 }, { kind: "pdf", page: 132 }, EXPLAINS],
    },
    {
      kind: "faq",
      id: "faq",
      heading: "Questions about digital asset import",
      items: [
        {
          question: "Do assets imported by different routes end up in separate libraries?",
          answer: ["No. GetSibu is designed as ", { text: "a unified environment", page: 150 }, " for managing creative content from multiple storage sources, retaining organisational structure and access controls, so a route is a way in rather than a library of its own."],
        },
        {
          question: "How can a team see whether new material is reaching the library at all?",
          answer: ["Look at the inflow rather than individual files. ", { text: "Upload analytics", page: 184 }, " show how much new content is entering the library over time, so a route that has quietly stopped carrying anything shows up as a gap."],
        },
        {
          question: "Is digital asset import the same as a migration?",
          answer: ["Not quite. ", { text: "A DAM migration", page: 376 }, " is the process of moving an existing collection into another asset management environment, usually once; import routes go on feeding the library long after any migration has finished."],
        },
      ],
      sources: [{ kind: "pdf", page: 150 }, { kind: "pdf", page: 184 }, { kind: "pdf", page: 376 }, EXPLAINS],
    },
    {
      kind: "related",
      id: "related",
      heading: "More on the routes into GetSibu",
      variant: "compact",
      pages: [121, 127, 128, 130, 262, 184],
      sources: [{ kind: "editorial", note: "Links to pages cited on this page." }],
    },
    {
      kind: "cta",
      id: "cta",
      heading: "Start Your Creative Library",
      conversionPage: 391,
      surface: "inverse",
      actions: [{ kind: "global", cta: "primary" }],
      sources: [{ kind: "pdf", page: 391 }],
    },
  ],
};

export default page;
