/**
 * Claims register.
 *
 * Every factual claim that could embarrass GetSibu if it were wrong: numbers, limits,
 * certifications, compliance, named third parties, plan contents, security mechanisms, AI
 * capabilities. Each carries its sources, its official-site wording and any conflict found.
 *
 * Why this exists: the PDF was written from "supplied website content" (PDF p.389-390), and the
 * official website audited on 2026-09-14 contains template placeholders (a "Lumen" brand, stock-photo
 * testimonials, hard-coded ROI figures) and claims the product's own code contradicts. Being on the
 * website is therefore not proof. See docs/architecture/02-source-audit.md.
 *
 * Publishing rule (enforced by scripts/validate-inventory.ts via `isPublishable`):
 *   client-confirmed                              → publishable
 *   standard risk + (site-stated | pdf-stated)    → publishable, in PDF/site wording
 *   everything else                               → blocked until GetSibu confirms it
 */
import type { Claim, SourceRef } from "../../types/content.ts";

const SITE = (path: string): SourceRef => ({ kind: "site", url: `https://getsibu.com${path}`, retrieved: "2026-09-14" });
const HOME = SITE("/");
const PRICING = SITE("/pricing");

export const CLAIMS: Claim[] = [
  /* Performance ----------------------------------------------------------------------------- */
  {
    id: "sub-second-search",
    statement: "Sub-second search across large libraries.",
    status: "site-stated",
    risk: "high",
    pdfPages: [20, 310],
    siteWording: ["Sub-second search across millions of assets.", "Sub-second index < 200 ms search latency p95"],
    evidence: [HOME],
    detect: ["sub-second", "200 ms", "p95"],
    note: "PDF hedges as \"stated performance positioning\". A latency figure needs a measured source.",
  },
  {
    id: "upload-10gb",
    statement: "Resumable, chunked uploads for files up to 10 GB.",
    status: "site-stated",
    risk: "high",
    pdfPages: [140],
    siteWording: ["Chunked uploads 10 GB per file, resumable", "Up to 10 GB per file out of the box; configurable in Settings → Storage."],
    conflicts: ["The public billing-plans API reports uploadMbPerFile: 0 (unset) for every plan."],
    evidence: [HOME],
    detect: ["10 GB", "10GB"],
  },
  {
    id: "cdn-latency",
    statement: "CDN streaming and edge previews with stated latency figures.",
    status: "site-stated",
    risk: "high",
    pdfPages: [],
    siteWording: ["CDN streaming < 50 ms first byte, globally", "Edge previews < 1 s preview-on-demand", "CDN + WAF Cloudflare edge · TLS 1.3"],
    evidence: [HOME],
    detect: ["50 ms", "first byte", "Cloudflare", "TLS 1.3"],
    note: "Site-only figures. The PDF names CDN delivery and edge caching without numbers.",
  },
  {
    id: "cdn-edge",
    statement: "CDN delivery and edge caching of previews and media.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [304, 305, 309, 314],
    evidence: [HOME],
    detect: ["CDN", "edge caching"],
  },
  {
    id: "architecture-internals",
    statement: "Layered architecture; stateless, autoscaled API tier; text + embedding search; per-tenant storage partitions; observability.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [301, 315, 316, 317, 318, 319],
    siteWording: ["API tier Express · stateless · autoscaled", "Search Mongo $text · embeddings", "Per-tenant data partitions", "OpenTelemetry observability"],
    evidence: [HOME],
    detect: ["stateless", "embedding-based", "OpenTelemetry"],
    note: "Name specific technologies (Express, MongoDB, OpenTelemetry) only if GetSibu wants its stack public.",
  },
  {
    id: "uptime",
    statement: "99.99% API uptime.",
    status: "site-stated",
    risk: "high",
    pdfPages: [],
    siteWording: ["99.99% API uptime"],
    conflicts: ["No status page or SLA document exists (status.getsibu.com has no DNS)."],
    evidence: [HOME],
    detect: ["99.99", "uptime"],
  },

  /* Security & compliance ------------------------------------------------------------------- */
  {
    id: "aes-256",
    statement: "AES-256 encryption at rest.",
    status: "site-stated",
    risk: "high",
    pdfPages: [322],
    siteWording: ["AES-256 at rest", "Storage S3 · per-tenant prefix · AES-256"],
    conflicts: ["Product code confirms AES-256-GCM only for stored secrets, not for asset storage."],
    evidence: [HOME],
    detect: ["AES-256", "AES 256", "encrypted at rest", "encryption at rest"],
  },
  {
    id: "encrypted-secrets",
    statement: "OAuth credentials, SMTP passwords and API tokens stored as encrypted secrets.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [323],
    siteWording: ["Encrypted secrets (OAuth keys, SMTP passwords, API tokens) using AES-256-GCM with rotating IVs."],
    evidence: [HOME],
    detect: ["SMTP password", "encrypted secret"],
    note: "The one encryption claim the product code also supports.",
  },
  {
    id: "soc2",
    statement: "Security architecture positioned as SOC 2 Type II ready.",
    status: "site-stated",
    risk: "high",
    pdfPages: [330],
    siteWording: ["SOC 2 Type II ready", "tenant-isolation controls under SOC 2 CC6 / CC7"],
    evidence: [HOME],
    detect: ["SOC 2", "SOC2", "Type II"],
    note: "\"Ready\" is not \"certified\" or \"compliant\". Never render as a badge or certification mark.",
  },
  {
    id: "gdpr",
    statement: "GDPR controls: EU-region storage and right-to-erasure.",
    status: "site-stated",
    risk: "high",
    pdfPages: [328],
    siteWording: ["EU-region storage, right-to-erasure cascade"],
    conflicts: ["No privacy policy exists on the site (footer Privacy link is \"#\")."],
    evidence: [HOME],
    detect: ["GDPR", "EU-region", "right-to-erasure", "right to erasure"],
  },
  {
    id: "data-regions",
    statement: "Workspace data region choice: US, EU, India or AP-Southeast; GetSibu never trains on customer data.",
    status: "site-stated",
    risk: "high",
    pdfPages: [],
    siteWording: ["Choose US, EU, India or AP-Southeast at workspace creation.", "GetSibu never trains on your data."],
    evidence: [HOME],
    detect: ["AP-Southeast", "never trains"],
  },
  {
    id: "dpa",
    statement: "Data Processing Agreement support.",
    status: "conflicting",
    risk: "high",
    pdfPages: [329],
    siteWording: ["signed data-processing addendum on every paid plan", "Invoices and DPAs available on every plan.", "custom DPAs"],
    conflicts: ["\"every paid plan\" vs \"every plan\" vs \"Business and Enterprise plans include … custom DPAs\"."],
    evidence: [HOME, PRICING],
    detect: ["DPA", "DPAs", "Data Processing Agreement", "data-processing addendum"],
  },
  {
    id: "immutable-audit",
    statement: "Immutable audit log of privileged actions.",
    status: "site-stated",
    risk: "high",
    pdfPages: [327],
    siteWording: ["Every login, permission change, AI generation, comment edit and asset delete writes to an immutable audit log."],
    evidence: [HOME],
    detect: ["immutable"],
  },
  {
    id: "backups-pitr",
    statement: "Backup redundancy and point-in-time restore.",
    status: "site-stated",
    risk: "high",
    pdfPages: [331, 332],
    siteWording: ["Daily snapshots, point-in-time restore to 7 days"],
    evidence: [HOME],
    detect: ["point-in-time", "daily snapshots", "backup redundancy"],
  },
  {
    id: "cross-region-replication",
    statement: "Cross-region replication on higher plans.",
    status: "conflicting",
    risk: "high",
    pdfPages: [333],
    siteWording: ["cross-region replication on Business+ plans"],
    conflicts: ["Same section says \"every plan inherits the same isolation, encryption and audit guarantees\"."],
    evidence: [HOME],
    detect: ["cross-region"],
  },
  {
    id: "sso-scim",
    statement: "SSO and SCIM, and which plan includes them.",
    status: "conflicting",
    risk: "high",
    pdfPages: [334, 335, 344, 389],
    siteWording: ["SSO & SCIM (Business plan card)", "SAML 2.0 and OIDC SSO on Business+. SCIM 2.0 user provisioning on Enterprise."],
    conflicts: ["SCIM on the Business card vs \"on Enterprise\" in the FAQ; SSO \"Business\" vs \"Business+\"."],
    evidence: [HOME, PRICING],
    detect: ["SSO", "SCIM", "single sign-on", "SAML", "OIDC"],
  },
  {
    id: "mfa",
    statement: "Multi-factor authentication, enforceable per organisation.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [336],
    siteWording: ["Force-MFA per-org enforced server-side."],
    evidence: [HOME],
    detect: ["MFA", "multi-factor", "2FA"],
  },
  {
    id: "default-deny",
    statement: "New folders are private until access is granted.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [154, 337],
    siteWording: ["New folders are private until granted. Managers can only see folders an Org Admin handed them."],
    evidence: [HOME],
    detect: ["default-deny"],
  },
  {
    id: "rbac-roles",
    statement: "Built-in roles: owner, administrator, manager, editor, individual user.",
    status: "conflicting",
    risk: "standard",
    pdfPages: [153],
    siteWording: ["Owner, admin, manager, editor, individual — with folder-level overrides", "Owner / Admin / Manager / User roles", "Five built-in roles."],
    conflicts: ["Three different role descriptions on the site; one lists four roles."],
    evidence: [HOME],
    detect: ["owners, administrators", "five built-in roles", "Owner, admin"],
    note: "Use the PDF's list (which matches the feature card) only after GetSibu confirms the role set.",
  },

  /* Multi-tenancy --------------------------------------------------------------------------- */
  {
    id: "multi-tenant",
    statement: "Multi-tenant design with each organisation isolated.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [160, 161, 162, 167, 324, 387],
    siteWording: ["Each organisation isolated end-to-end. Per-tenant keys, scoped queries, audit logs.", "Tenant per client"],
    evidence: [HOME],
    detect: ["multi-tenant", "tenant isolation", "tenant-scoped"],
  },
  {
    id: "per-client-config",
    statement: "Per-client SSO, storage quotas and AI keys.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [163, 164, 165],
    siteWording: ["Per-client SSO, per-client storage quotas, per-client AI keys."],
    evidence: [HOME],
    detect: ["per-client"],
  },
  {
    id: "white-label",
    statement: "White-label client-facing asset management.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [166],
    siteWording: ["White-label"],
    evidence: [HOME],
    detect: ["white-label"],
  },
  {
    id: "self-host",
    statement: "Self-host option on Business and Enterprise plans.",
    status: "site-stated",
    risk: "high",
    pdfPages: [],
    siteWording: ["Business and Enterprise plans include a self-host option. We ship a Docker Compose bundle (API + MongoDB + Redis + worker) and an OpenAPI spec"],
    evidence: [HOME],
    detect: ["self-host", "Docker Compose"],
  },

  /* AI -------------------------------------------------------------------------------------- */
  {
    id: "ai-tagging",
    statement: "AI-assisted tagging with confidence, bulk approval and override.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [9, 31, 46, 47, 48, 383],
    siteWording: ["Suggested tags and scene detection on import. Approve in bulk, override anytime.", "Detects objects, scenes, mood, colours, faces — with confidence scores."],
    evidence: [HOME],
    detect: ["AI-assisted tagging", "confidence score"],
  },
  {
    id: "ai-vision-attributes",
    statement: "Vision analysis of objects, scenes, mood and colours.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [32, 34, 35, 36],
    siteWording: ["Vision-grounded auto-tagging. Detects objects, scenes, mood, colours, faces — with confidence scores."],
    evidence: [HOME],
    detect: ["mood detection", "colour detection", "object detection"],
  },
  {
    id: "scene-detection",
    statement: "Automatic scene detection in video.",
    status: "conflicting",
    risk: "high",
    pdfPages: [3, 33, 51, 212, 216, 217, 365],
    siteWording: ["Break video into structured scenes — automatically. Jump between scenes from the asset page or via API."],
    conflicts: ["The product's AI settings label it \"Scene detection — Key moments in video (coming soon).\""],
    evidence: [HOME],
    detect: ["scene detection", "scenes"],
    note: "Pages 33 and 365 can still exist; copy must not state availability until confirmed.",
  },
  {
    id: "face-grouping",
    statement: "Face grouping clusters people across the library.",
    status: "site-stated",
    risk: "high",
    pdfPages: [3, 37, 367],
    siteWording: ["Cluster people across your library. Find every shot of the founder, the talent, the client — instantly."],
    conflicts: ["Not present in the product code; appears only in landing-page code."],
    evidence: [HOME],
    detect: ["face grouping", "faces"],
    note: "Biometric processing also has privacy implications; confirm availability and data handling.",
  },
  {
    id: "ocr",
    statement: "OCR text extraction from images, PDFs, presentations and screenshots.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [15, 38, 53, 366, 384],
    siteWording: ["Pulls text out of images, PDFs, presentations and screenshots."],
    evidence: [HOME],
    detect: ["OCR"],
  },
  {
    id: "semantic-search",
    statement: "Semantic, embeddings-aware search.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [14, 18, 39, 49, 317, 363],
    siteWording: ["Embeddings-aware retrieval.", "GetSibu's search blends full-text, OCR, AI tags and embeddings."],
    evidence: [HOME],
    detect: ["semantic search", "embeddings"],
  },
  {
    id: "duplicate-detection",
    statement: "Duplicate detection using exact and perceptual hashing.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [40, 112, 368],
    siteWording: ["Perceptual + exact hash. Catches re-encoded copies even when filenames lie."],
    evidence: [HOME],
    detect: ["perceptual", "duplicate detection"],
  },
  {
    id: "auto-collections",
    statement: "AI-proposed collections approved by users.",
    status: "site-stated",
    risk: "high",
    pdfPages: [41, 56],
    siteWording: ["GetSibu proposes folders (\"Q3 product shots\", \"Team headshots\") based on what it sees. You approve, it organises."],
    conflicts: ["Not present in the product code; appears only in landing-page code."],
    evidence: [HOME],
    detect: ["auto collections", "proposes folders"],
  },
  {
    id: "transcription",
    statement: "AI subtitle and transcript generation.",
    status: "site-stated",
    risk: "high",
    pdfPages: [],
    siteWording: ["AI subtitle generation (9+ languages)", "One-click multilingual transcripts powered by Whisper, downloadable as SRT / VTT."],
    evidence: [HOME],
    detect: ["subtitle", "transcript", "Whisper", "SRT"],
    note: "Site-only capability; no PDF page. Do not add pages for it.",
  },

  /* Collaboration & search ------------------------------------------------------------------ */
  {
    id: "timeline-comments",
    statement: "Comments attached to points on a video timeline.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [64, 385],
    siteWording: ["Threaded discussions on every asset — even at specific timecodes in video.", "Comments pinned to the timeline"],
    evidence: [HOME],
    detect: ["timecode", "timeline comment"],
  },
  {
    id: "frame-accurate",
    statement: "Frame-accurate video review.",
    status: "pdf-stated",
    risk: "standard",
    pdfPages: [65],
    detect: ["frame-accurate"],
    note: "Site says \"specific timecodes\"; \"frame-accurate\" is the PDF's term.",
  },
  {
    id: "folder-aware-mentions",
    statement: "Mentions with folder-aware autocomplete.",
    status: "pdf-stated",
    risk: "standard",
    pdfPages: [66],
    siteWording: ["@-mentions", "Threaded comments + mentions"],
    detect: ["folder-aware"],
  },
  {
    id: "saved-search-urls",
    statement: "Saved searches shareable by URL.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [17, 79],
    siteWording: ["Saved searches share by URL."],
    evidence: [HOME],
    detect: ["share by URL", "through a URL"],
  },
  {
    id: "taxonomy",
    statement: "Hierarchical tags with synonyms, colour and inheritance.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [8],
    siteWording: ["Hierarchical tags with synonyms, colour, and inheritance. Bulk re-tag in a click."],
    evidence: [HOME],
    detect: ["synonyms", "inheritance"],
  },

  /* Storage & ingestion --------------------------------------------------------------------- */
  {
    id: "storage-sources",
    statement: "Connectable storage sources: Google Drive, Dropbox, OneDrive, AWS S3 and local NAS.",
    status: "site-stated",
    risk: "high",
    pdfPages: [122, 123, 124, 125, 126, 242, 243, 244, 245, 283, 284, 285],
    siteWording: ["Connect Google Drive, local NAS, or drag & drop.", "Google Drive", "Dropbox", "OneDrive", "AWS S3"],
    evidence: [HOME],
    detect: ["Google Drive", "Dropbox", "OneDrive", "AWS S3", "NAS"],
    note: "Product code shows OAuth for OneDrive, ingest sources for Drive, Dropbox, S3-compatible and a NAS agent. Confirm each is generally available.",
  },
  {
    id: "watch-folders",
    statement: "Watch folders scanned continuously.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [128],
    siteWording: ["Watch folders are scanned continuously."],
    evidence: [HOME],
    detect: ["watch folder", "watch folders"],
  },
  {
    id: "metadata-preserved",
    statement: "EXIF, XMP, creators, file paths and custom keywords preserved on import and migration.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [22, 132, 286],
    siteWording: ["Metadata preserved"],
    evidence: [HOME],
    detect: ["EXIF", "XMP"],
    note: "The site names the step; the field list comes from the PDF.",
  },
  {
    id: "migration-no-downtime",
    statement: "Existing storage stays usable while content is indexed in the background.",
    status: "pdf-stated",
    risk: "standard",
    pdfPages: [292],
    detect: ["without downtime"],
  },
  {
    id: "permission-translation",
    statement: "Permissions translate from Google Workspace groups during migration.",
    status: "site-stated",
    risk: "high",
    pdfPages: [295],
    siteWording: ["Permissions translate from G Suite groups."],
    evidence: [HOME],
    detect: ["G Suite", "Google Workspace groups"],
  },
  {
    id: "onboarding-assistance",
    statement: "Onboarding with rollout, training and data verification on higher plans.",
    status: "site-stated",
    risk: "high",
    pdfPages: [297],
    siteWording: ["Onboarding included", "White-glove rollout on Business+."],
    evidence: [HOME],
    detect: ["white-glove", "team training"],
  },

  /* Integrations ---------------------------------------------------------------------------- */
  { id: "slack", statement: "Slack integration.", status: "site-stated", risk: "high", pdfPages: [246, 390], siteWording: ["Out-of-the-box for Slack and Webhooks"], evidence: [HOME], detect: ["Slack"] },
  { id: "zapier", statement: "Zapier integration.", status: "site-stated", risk: "high", pdfPages: [251, 390], siteWording: ["automate with Zapier"], evidence: [HOME], detect: ["Zapier"] },
  { id: "frame-io", statement: "Frame.io integration.", status: "site-stated", risk: "high", pdfPages: [250, 390], siteWording: ["Premiere/AE/Frame.io via our extensions and Zapier."], evidence: [HOME], detect: ["Frame.io"] },
  {
    id: "figma",
    statement: "Figma integration.",
    status: "conflicting",
    risk: "high",
    pdfPages: [247, 390],
    siteWording: ["Figma (integrations grid)"],
    conflicts: ["Product integrations page lists Figma as \"Not supported\" (\"Figma's public REST API is read-only for files.\")."],
    evidence: [HOME],
    detect: ["Figma"],
  },
  {
    id: "adobe-premiere-after-effects",
    statement: "Adobe Premiere Pro and After Effects integrations.",
    status: "conflicting",
    risk: "high",
    pdfPages: [248, 249, 390],
    siteWording: ["Premiere Pro", "After Effects", "Premiere/AE/Frame.io via our extensions and Zapier."],
    conflicts: ["Product integrations page lists both as \"Not supported\" (requires an Adobe UXP plugin)."],
    evidence: [HOME],
    detect: ["Premiere Pro", "After Effects", "Premiere"],
  },
  {
    id: "integration-turnaround",
    statement: "Requested integrations ship in under two weeks.",
    status: "site-stated",
    risk: "high",
    pdfPages: [],
    siteWording: ["most ship in under 2 weeks"],
    evidence: [HOME],
    detect: ["2 weeks", "two weeks"],
  },

  /* Developers ------------------------------------------------------------------------------ */
  {
    id: "rest-api-first",
    statement: "API-first DAM with a REST API used by the product itself.",
    status: "site-stated",
    risk: "standard",
    pdfPages: [253, 254, 261, 388],
    siteWording: ["GetSibu is an API-first DAM. The UI is just one of many possible clients.", "Every page in the app uses the same endpoints."],
    evidence: [HOME],
    detect: ["API-first", "REST API"],
  },
  {
    id: "webhook-events",
    statement: "Webhook events such as asset created, comment added, approval requested and billing events.",
    status: "conflicting",
    risk: "high",
    pdfPages: [252, 268, 269, 270, 271, 272],
    siteWording: ["Subscribe to asset.created, comment.added, approval.requested, billing.expired and more."],
    conflicts: ["Product webhook settings show \"asset.created,asset.deleted,ticket.created\" as example events; comment/approval events not found."],
    evidence: [HOME],
    detect: ["asset.created", "comment.added", "approval.requested", "billing.expired"],
    note: "Product code confirms HMAC-signed webhooks with retry and exponential backoff.",
  },
  {
    id: "openapi",
    statement: "OpenAPI 3.1 specification.",
    status: "conflicting",
    risk: "high",
    pdfPages: [259, 274],
    siteWording: ["Documented OpenAPI 3.1 spec."],
    conflicts: ["No public documentation: Documentation and API reference links are \"#\", /api/v1/openapi.json returns 401, docs.getsibu.com has no DNS."],
    evidence: [HOME],
    detect: ["OpenAPI"],
  },
  {
    id: "sdks",
    statement: "TypeScript, Python and Go SDKs.",
    status: "conflicting",
    risk: "high",
    pdfPages: [259],
    siteWording: ["TypeScript, Python and Go SDKs. Generated from the OpenAPI spec — never out of date."],
    conflicts: ["PDF calls it \"stated developer direction\"; no SDK references exist in the product code."],
    evidence: [HOME],
    detect: ["SDK", "SDKs"],
  },
  {
    id: "developer-playground",
    statement: "Built-in API playground.",
    status: "conflicting",
    risk: "high",
    pdfPages: [258],
    siteWording: ["Built-in playground in Settings → Developer. Sign requests, replay, copy as curl."],
    conflicts: ["The product's settings page is \"API & Webhooks\" and contains no playground."],
    evidence: [HOME],
    detect: ["playground"],
  },

  /* Pricing --------------------------------------------------------------------------------- */
  {
    id: "pricing-tiers",
    statement: "Free, Pro and Business plans.",
    status: "conflicting",
    risk: "high",
    pdfPages: [341, 342, 343, 344],
    siteWording: ["Free $0 forever", "Pro $99 / month", "Business $299 / month"],
    conflicts: ["The signup plan API also returns Starter ($29), Enterprise (contact sales), Lifetime ($499, twice) and a \"TestJM\" plan."],
    evidence: [PRICING],
    detect: ["Free plan", "Pro plan", "Business plan", "$99", "$299", "per month", "/ month"],
  },
  {
    id: "free-plan-limits",
    statement: "Free plan: 5 GB storage, 3 seats, 10k API calls per month, drag-and-drop upload, search and tags.",
    status: "site-stated",
    risk: "high",
    pdfPages: [342],
    siteWording: ["5 GB storage", "3 seats", "10k API calls / mo", "Drag & drop upload", "Search & tags"],
    evidence: [PRICING],
    detect: ["5 GB", "three seats", "3 seats", "10k API calls"],
  },
  {
    id: "pro-plan-contents",
    statement: "Pro plan: 500 GB, 20 seats, 1M API calls/month, Google Drive sync, threaded comments and mentions, saved searches; 3-day trial.",
    status: "site-stated",
    risk: "high",
    pdfPages: [343],
    siteWording: ["500 GB storage", "20 seats", "1M API calls / mo", "Google Drive sync", "Threaded comments + mentions", "Saved searches", "Start 3-day trial"],
    evidence: [PRICING],
    detect: ["500 GB", "20 seats", "3-day trial"],
  },
  {
    id: "business-plan-contents",
    statement: "Business plan: 2 TB, 100 seats, 5M API calls/month, SSO & SCIM, audit log export, priority support.",
    status: "conflicting",
    risk: "high",
    pdfPages: [344],
    siteWording: ["2 TB storage", "100 seats", "5M API calls / mo", "SSO & SCIM", "Audit log export", "Priority support"],
    conflicts: ["SCIM is \"on Enterprise\" in the homepage FAQ."],
    evidence: [PRICING],
    detect: ["2 TB", "100 seats", "audit log export", "priority support"],
  },
];

/**
 * Official-site content that must never be reused: template leftovers and placeholders.
 * The validator fails any authored content containing these strings.
 */
export const DO_NOT_USE: Array<{ text: string; reason: string }> = [
  { text: "Lumen", reason: "Template brand left in the homepage mock-up, code sample and contact emails." },
  { text: "lumendam", reason: "Template domain in code sample and FAQ email." },
  { text: "Maya Park", reason: "Placeholder person used as both CEO and a customer testimonial." },
  { text: "Jordan Reyes", reason: "Placeholder person used as both CTO and a customer testimonial." },
  { text: "Priya Shah", reason: "Placeholder person used as both Head of Product and a customer testimonial." },
  { text: "Leo Müller", reason: "Placeholder team member with stock photo." },
  { text: "555-0144", reason: "Reserved fictional phone number range." },
  { text: "PixelForge", reason: "Unverified \"trusted by\" name, rendered as plain text." },
  { text: "Studio Nova", reason: "Unverified \"trusted by\" name." },
  { text: "MotionLab", reason: "Unverified \"trusted by\" name." },
  { text: "North Pier", reason: "Unverified \"trusted by\" name and testimonial company." },
  { text: "Atlas Films", reason: "Unverified \"trusted by\" name." },
  { text: "Lattice Studio", reason: "Testimonial company attached to a placeholder person." },
  { text: "Brand Republic", reason: "Testimonial company attached to a placeholder person." },
  { text: "GetSibu Labs", reason: "Self-referential entry in the \"trusted by\" strip." },
  { text: "78%", reason: "Hard-coded ROI figure (\"78% faster discovery\")." },
  { text: "12 hrs/wk", reason: "Hard-coded ROI figure." },
  { text: "4× fewer duplicates", reason: "Hard-coded ROI figure." },
  { text: "1,200+", reason: "\"Trusted by 1,200+ creative teams\" conflicts with \"12 studios\" in beta." },
  { text: "14,250", reason: "Hard-coded \"frames analysed in the last hour\" counter." },
  { text: "50 TB of unsorted footage", reason: "Unverified origin story on the placeholder About page." },
];

export const claimById = new Map(CLAIMS.map((c) => [c.id, c]));

export function isPublishable(claim: Claim): boolean {
  if (claim.status === "client-confirmed") return true;
  return claim.risk === "standard" && (claim.status === "site-stated" || claim.status === "pdf-stated");
}
