/**
 * Topic clusters.
 *
 * A cluster is a set of pages about the same topic, across any section. Clusters drive:
 *   - related links (a feature page links to its explainer, FAQ and use cases)
 *   - index-page grouping (see `groupBy` in sections.ts)
 *   - duplicate prevention: where PDF paragraphs are near-identical (`overlapRisk: "high"`), each
 *     page gets an `angle` taken from where the PDF places it. Authors write to that angle.
 *
 * Every canonical PDF page belongs to at least one cluster (enforced by validate-inventory).
 * `primary` is the pillar page for the topic; other members link to it.
 */
import type { TopicCluster } from "../../types/content.ts";

export const CLUSTERS: TopicCluster[] = [
  /* Platform ------------------------------------------------------------------------------- */
  {
    id: "platform-positioning",
    label: "What GetSibu is",
    primary: 1,
    members: [1, 2, 3, 5, 7, 120, 360, 381, 382],
    overlapRisk: "medium",
    angles: {
      1: "Homepage: the platform in one statement — store, organise, search, review and collaborate from one workspace.",
      2: "The operating-system idea: storage, organisation, AI tagging, search, collaboration, permissions and analytics as one platform.",
      3: "Why AI belongs in DAM: the manual work AI tagging, scene detection, OCR, semantic search, face grouping and duplicate detection remove.",
      5: "From media library to information system: search by what is in the asset, not its filename.",
      7: "Contrast with traditional file storage: what DAM adds for creative workflows.",
      120: "Everything combined: organisation, metadata, AI, collaboration, versioning, approvals, auditability as one workflow.",
      360: "Investment case summary for decision makers.",
      381: "FAQ: one-sentence definition.",
      382: "FAQ: the audiences GetSibu is designed for.",
    },
  },
  {
    id: "centralisation",
    label: "One central library",
    primary: 6,
    members: [1, 6, 10, 150, 373, 392, 395],
    overlapRisk: "medium",
    angles: {
      6: "Bringing connected drives, local infrastructure and uploads into one location; fewer disconnected versions.",
      10: "A shared source of truth across creative, marketing, production and brand teams, governed by permissions and approvals.",
      150: "The storage view: one environment across multiple sources that keeps organisational structure and access controls.",
      373: "Vendor-neutral explainer: what a creative library is.",
    },
  },
  {
    id: "library-organisation",
    label: "Organising the library",
    primary: 8,
    members: [4, 8, 29, 57, 375, 397, 399],
    overlapRisk: "medium",
    angles: {
      4: "Structure for a growing library: folders, tags, collections, metadata and permissions.",
      8: "Taxonomy that scales: hierarchical tags, synonyms, colours and inheritance.",
      29: "Moving through the library: views, folders, tags, collections and search.",
      57: "AI keeping the library in order as it grows, instead of periodic manual clean-ups.",
      375: "Vendor-neutral explainer: what an asset taxonomy is.",
    },
  },

  /* Search & Discovery ---------------------------------------------------------------------- */
  {
    id: "creative-search",
    label: "Creative asset search",
    primary: 11,
    members: [5, 11, 13, 16, 23, 24, 393],
    overlapRisk: "high",
    angles: {
      5: "Platform framing (see platform-positioning): the media library as an information system.",
      11: "The signals search uses: filenames, metadata, OCR, AI-generated tags, comments and semantic information.",
      13: "The dedicated media search experience: keywords combined with category, format, uploader, resolution and date filters.",
      16: "Library-wide scope: searching everything at once instead of opening folders one by one.",
      23: "Metadata as a search path when filename and folder are unknown.",
      24: "One unified search across images, video, audio and documents, reducing reliance on folder knowledge.",
      393: "Conversion: search by what you remember instead of folder structures.",
    },
  },
  {
    id: "semantic-search",
    label: "Semantic and natural language search",
    primary: 39,
    members: [14, 18, 39, 49, 317, 363],
    overlapRisk: "high",
    angles: {
      14: "In the search box: describing a creative need (\"warm urban evening footage\") and how embeddings and AI media information interpret it.",
      18: "How people remember assets — colour, scene, subject, location, campaign — and searching that way.",
      39: "The AI capability: interpreting meaning rather than exact words.",
      49: "The outcome for creative work: describe the asset, receive results from semantic and visual information.",
      317: "Infrastructure: text search combined with embedding-based retrieval.",
      363: "Vendor-neutral explainer: what semantic search is.",
    },
  },
  {
    id: "ocr-search",
    label: "OCR and text inside assets",
    primary: 38,
    members: [15, 27, 38, 53, 366, 384],
    overlapRisk: "high",
    angles: {
      15: "Search angle: finding assets by the text inside images, PDFs, presentations and screenshots.",
      27: "Document library angle: indexing documents by extracted text, metadata and tags.",
      38: "AI capability angle: the extraction itself and what becomes part of searchable asset information.",
      53: "Discovery angle: OCR combined with metadata to locate documents.",
      366: "Vendor-neutral explainer: what OCR means in DAM.",
      384: "FAQ: direct yes/no answer.",
    },
  },
  {
    id: "filters-saved-searches",
    label: "Filters and saved searches",
    primary: 19,
    members: [13, 17, 19],
    overlapRisk: "high",
    angles: {
      13: "The search experience as a whole (see creative-search).",
      17: "Saving a frequently used search and sharing it through a URL.",
      19: "Filters themselves: categories, formats, sources, resolutions, dates, combined progressively.",
    },
  },
  {
    id: "indexing-metadata",
    label: "Indexing and metadata",
    primary: 22,
    members: [21, 22, 23, 50, 374],
    overlapRisk: "high",
    angles: {
      21: "What happens on entry: metadata processed into an indexed representation of the library.",
      22: "Metadata fields that become part of the asset record: EXIF, XMP, file paths, creators, custom keywords.",
      23: "Searching that metadata (see creative-search).",
      50: "AI's contribution to indexing: visual, textual and metadata signals prepared for discovery.",
      374: "Vendor-neutral explainer: what asset metadata is.",
    },
  },
  {
    id: "media-libraries",
    label: "Searchable libraries by media type",
    primary: 24,
    members: [24, 25, 26, 27, 28],
    overlapRisk: "medium",
    angles: {
      25: "Video: indexed and enriched so footage is found without reviewing every file.",
      26: "Images: searchable through metadata, tags and visual characteristics for reuse across campaigns.",
      27: "Documents: see ocr-search.",
      28: "Audio: managed alongside other formats rather than in a separate system.",
    },
  },
  {
    id: "discovery-workflow",
    label: "The discovery workflow",
    primary: 30,
    members: [12, 29, 30, 394],
    overlapRisk: "low",
  },
  {
    id: "search-speed",
    label: "Search speed",
    primary: 20,
    members: [20, 307, 310, 349],
    overlapRisk: "high",
    angles: {
      20: "Discovery outcome: indexing, metadata and AI-assisted retrieval reduce time spent looking for files.",
      307: "Architecture: low-latency search as a design goal of the infrastructure.",
      310: "Performance positioning: sub-second search as part of the user experience (claim — verify before publishing).",
      349: "Business value: time returned to creative work.",
    },
  },

  /* AI ------------------------------------------------------------------------------------- */
  {
    id: "ai-tagging",
    label: "AI-assisted tagging",
    primary: 31,
    members: [9, 31, 42, 46, 47, 48, 364, 383],
    overlapRisk: "medium",
    angles: {
      9: "Platform stance: AI recommends, teams approve in bulk or override, and keep control of organisation.",
      31: "The feature: tags suggested during processing, reviewed by authorised users.",
      42: "Classification: categorising assets by content and metadata.",
      46: "Confidence information and what it tells a reviewer.",
      47: "Bulk approval of suggested tags at library scale.",
      48: "Overriding tags that do not match the team's taxonomy.",
      364: "Vendor-neutral explainer: what AI tagging is.",
      383: "FAQ: direct yes answer.",
    },
  },
  {
    id: "ai-vision",
    label: "AI vision analysis",
    primary: 32,
    members: [32, 33, 34, 35, 36, 43],
    overlapRisk: "medium",
    angles: {
      32: "Umbrella: visual media analysed for objects, scenes, moods and colours that become searchable.",
      33: "Video broken into structured scenes for navigation.",
      34: "Objects identified with confidence information.",
      35: "Visual mood as searchable information.",
      36: "Colour characteristics extracted for discovery.",
      43: "Interpreting visual content for search and organisation workflows (see ai-intelligence).",
    },
  },
  {
    id: "scene-detection",
    label: "Scene detection and video",
    primary: 33,
    members: [33, 51, 212, 216, 217, 365],
    overlapRisk: "low",
  },
  {
    id: "face-grouping",
    label: "Face grouping",
    primary: 37,
    members: [37, 367],
    overlapRisk: "low",
  },
  {
    id: "duplicate-detection",
    label: "Duplicate detection",
    primary: 40,
    members: [40, 112, 350, 368],
    overlapRisk: "high",
    angles: {
      40: "The technique: exact plus perceptual hashing, catching renamed and re-encoded copies.",
      112: "Library housekeeping: identifying unnecessary copies to support storage optimisation.",
      350: "Business value: less storage consumption and less confusion from multiple copies.",
      368: "Vendor-neutral explainer: what duplicate detection is.",
    },
  },
  {
    id: "ai-collections",
    label: "AI collections and recommendations",
    primary: 41,
    members: [41, 56, 57],
    overlapRisk: "medium",
    angles: {
      41: "Proposed collections from patterns, approved by users.",
      56: "Recommendations for collections and organisational structures.",
      57: "Ongoing order as the library grows (see library-organisation).",
    },
  },
  {
    id: "ai-discovery",
    label: "AI-powered discovery",
    primary: 12,
    members: [12, 25, 26, 49, 51, 52, 53],
    overlapRisk: "high",
    angles: {
      12: "Finding files by what appears inside them, useful for visually similar libraries.",
      25: "Searchable video library (media-type angle).",
      26: "Searchable image library (media-type angle).",
      49: "AI creative search (see semantic-search).",
      51: "AI angle for video: search by scenes, objects and visual characteristics.",
      52: "AI angle for images: photographs, product shots, campaign images through AI-generated metadata.",
      53: "AI angle for documents (see ocr-search).",
    },
  },
  {
    id: "ai-intelligence",
    label: "AI media understanding",
    primary: 43,
    members: [43, 44, 50, 58, 380, 398],
    overlapRisk: "high",
    angles: {
      43: "Understanding: interpreting visual content and exposing it to search and organisation.",
      44: "Meaning: stored files become an information layer instead of anonymous files.",
      50: "Indexing: see indexing-metadata.",
      58: "Combination: AI analysis with metadata and search capabilities.",
      380: "Forward-looking essay: libraries as knowledge environments.",
      398: "Conversion: turning years of organisational content into a usable resource.",
    },
  },
  {
    id: "ai-approach",
    label: "Practical, human-controlled AI",
    primary: 60,
    members: [3, 9, 45, 54, 55, 59, 60, 362, 377],
    overlapRisk: "medium",
    angles: {
      3: "Platform positioning (see platform-positioning).",
      45: "Automated analysis combined with human approval; AI reduces library administration.",
      54: "AI as an operational layer from ingestion to discovery, not an isolated feature.",
      55: "Tasks automated: tagging, scene identification, OCR extraction, collection creation.",
      59: "For production and marketing teams: less time managing files.",
      60: "Focus: AI aimed at practical library problems with a workflow purpose.",
      362: "Vendor-neutral explainer: what AI asset management is.",
      377: "Essay: how AI changes DAM.",
    },
  },

  /* Collaboration -------------------------------------------------------------------------- */
  {
    id: "comments-feedback",
    label: "Comments and feedback",
    primary: 62,
    members: [61, 62, 63, 66, 73, 74, 75, 85, 86],
    overlapRisk: "high",
    angles: {
      61: "Collaboration inside the library instead of disconnected tools.",
      62: "Comments on assets, attached to the work.",
      63: "Threads that keep conversations organised by issue.",
      66: "Mentions with folder-aware autocomplete — people mentioned have visibility.",
      73: "Problem framing: feedback scattered across email, chat and project tools.",
      74: "Feedback as an organised workflow attached to the asset.",
      75: "How feedback evolved: discussion history.",
      85: "Communication kept close to the asset so its context is clear.",
      86: "Mentions as the way to bring the right collaborator in.",
    },
  },
  {
    id: "mentions",
    label: "Mentions",
    primary: 66,
    members: [66, 86],
    overlapRisk: "high",
    angles: {
      66: "The mechanism: folder-aware autocomplete for teammates with visibility.",
      86: "The purpose: involving the right collaborator in an asset-specific discussion.",
    },
  },
  {
    id: "video-review",
    label: "Video and creative review",
    primary: 64,
    members: [64, 65, 69, 81, 250, 385],
    overlapRisk: "medium",
    angles: {
      64: "Comments attached to timeline points.",
      65: "Discussing exact moments instead of approximate descriptions.",
      69: "A central place to inspect work, discuss changes and confirm finals.",
      81: "Production teams combining comments, versioning and timeline review.",
      250: "Connecting Frame.io review workflows with central asset management.",
      385: "FAQ: direct yes answer.",
    },
  },
  {
    id: "approvals",
    label: "Approvals",
    primary: 67,
    members: [67, 68, 69, 70, 71, 72, 76, 77, 89, 103, 267, 370],
    overlapRisk: "high",
    angles: {
      67: "The workflow: request review, make changes, mark approved.",
      68: "Status history: awaiting review, approved, requires changes.",
      69: "The review space: inspect work, discuss changes, confirm final assets.",
      70: "Campaign materials reviewed before distribution.",
      71: "Approval gates separating approved brand assets from drafts.",
      72: "Client-specific review with clients kept isolated.",
      76: "The status indicator: needs attention or completed.",
      77: "The record of review activity and which version was accepted.",
      89: "Managing the draft-to-approved process across the library.",
      103: "Approved-only views of the library.",
      267: "Approval events in external systems (API).",
      370: "Vendor-neutral explainer: what creative approval is.",
    },
  },
  {
    id: "sharing-views",
    label: "Saved and shared views",
    primary: 79,
    members: [17, 78, 79],
    overlapRisk: "high",
    angles: {
      17: "Saving a search for reuse (see filters-saved-searches).",
      78: "Sharing without creating duplicate copies of files.",
      79: "Recurring collections shared through a URL.",
    },
  },
  {
    id: "team-collaboration",
    label: "Collaboration by team",
    primary: 90,
    members: [61, 81, 82, 83, 84, 87, 88, 90, 379],
    overlapRisk: "medium",
    angles: {
      82: "Marketing: campaign libraries, approvals, usage analytics.",
      83: "Brand: approved assets organised by campaign, region or market.",
      84: "Agencies: multiple client libraries in a multi-tenant environment.",
      87: "Distributed review without being in the same location.",
      88: "Remote teams using comments, mentions, approvals and shared searches.",
      90: "The shared workspace itself.",
      379: "Essay: the future of creative collaboration.",
    },
  },
  {
    id: "creative-workflow",
    label: "End-to-end creative workflow",
    primary: 80,
    members: [54, 67, 80, 90, 107, 208, 396],
    overlapRisk: "medium",
  },

  /* Versioning & Asset Management ---------------------------------------------------------- */
  {
    id: "versioning",
    label: "Versioning",
    primary: 91,
    members: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 369, 386],
    overlapRisk: "medium",
    angles: {
      91: "Replace in place; the end of \"final-final\" filenames.",
      92: "The version record and restoring older versions.",
      93: "Replacement without losing previous work.",
      94: "Returning to a previous creative state.",
      95: "Context on how an asset changed over time.",
      96: "Campaign teams avoiding disconnected copies.",
      97: "Video cuts and revisions.",
      98: "Visual assets for marketing and design.",
      99: "Documents and presentations.",
      100: "What changed between versions and which is active.",
      369: "Vendor-neutral explainer: what asset versioning is.",
      386: "FAQ: direct yes answer.",
    },
  },
  {
    id: "asset-lifecycle",
    label: "Asset lifecycle",
    primary: 101,
    members: [101, 102, 104, 107, 108, 109, 110],
    overlapRisk: "high",
    angles: {
      101: "Managing the lifecycle from upload through review, approval, reuse and deletion.",
      102: "Statuses that distinguish drafts from approved content.",
      104: "Expiry information for content that should no longer be used.",
      107: "The stages enumerated: ingestion, metadata, AI tagging, review, approval, distribution, archival.",
      108: "Retaining history without cluttering everyday discovery.",
      109: "Removal according to policy and permissions.",
      110: "Recovery through versioning and backups.",
    },
  },
  {
    id: "brand-control",
    label: "Brand control",
    primary: 103,
    members: [71, 83, 103, 104, 105, 203, 214],
    overlapRisk: "low",
  },
  {
    id: "library-maintenance",
    label: "Library maintenance and quality",
    primary: 111,
    members: [111, 112, 113, 196],
    overlapRisk: "low",
  },
  {
    id: "usage-tracking",
    label: "Usage tracking",
    primary: 182,
    members: [106, 182, 197, 204],
    overlapRisk: "high",
    angles: {
      106: "Lifecycle angle: which assets are used and which remain inactive.",
      182: "Analytics angle: attention and under-use.",
      197: "How content is viewed or used.",
      204: "Patterns in asset usage.",
    },
  },
  {
    id: "governance",
    label: "Governance",
    primary: 114,
    members: [114, 159, 179, 339, 371],
    overlapRisk: "high",
    angles: {
      114: "Asset governance: who can upload, edit, approve, download and manage.",
      159: "Access governance: control over sensitive content.",
      179: "Enterprise governance: roles, permissions, audit logs, authentication and policies combined.",
      339: "Data governance: rules for access, retention, usage and management.",
      371: "Vendor-neutral explainer: what creative governance is.",
    },
  },
  {
    id: "audit-history",
    label: "Audit trail and history",
    primary: 119,
    members: [77, 115, 116, 117, 118, 119, 170, 326, 327],
    overlapRisk: "high",
    angles: {
      77: "Approval record (see approvals).",
      115: "Ownership: who created or uploaded.",
      116: "Attribution: creators and contributors preserved through collaboration and migration.",
      117: "History: relevant changes and interactions.",
      118: "Activity: views, downloads, edits and approvals.",
      119: "Asset audit trail: visibility into important actions on creative files.",
      170: "Permission changes recorded.",
      326: "Platform audit logs: permissions, comments, asset changes and other events.",
      327: "Immutability of privileged-action records.",
    },
  },

  /* Storage & Ingestion -------------------------------------------------------------------- */
  {
    id: "storage-connectors",
    label: "Storage sources",
    primary: 150,
    members: [122, 123, 124, 125, 126, 150],
    overlapRisk: "low",
  },
  {
    id: "ingestion",
    label: "Ingestion and import",
    primary: 121,
    members: [121, 127, 128, 129, 130, 135, 391],
    overlapRisk: "high",
    angles: {
      121: "Overview: connected sources and direct uploads without rebuilding the storage workflow.",
      127: "Drag and drop for individual assets and small batches.",
      128: "Watch folders scanned continuously.",
      129: "Reducing manual movement of files between locations.",
      130: "Bulk import for large existing libraries (see bulk-import).",
      135: "Multiple entry points as flexibility in building a library.",
      391: "Conversion: connect a source or upload files and let the library build.",
    },
  },
  {
    id: "bulk-import",
    label: "Bulk import",
    primary: 130,
    members: [130, 291],
    overlapRisk: "high",
    angles: {
      130: "Ingestion mechanics: moving a large existing library in without uploading file by file.",
      291: "Migration step: moving large quantities of media as part of a planned migration.",
    },
  },
  {
    id: "uploads",
    label: "Uploads",
    primary: 136,
    members: [127, 136, 137, 138, 139, 140, 141, 142, 312],
    overlapRisk: "medium",
    angles: {
      136: "Upload management: progress and resumable transfers on unreliable networks.",
      137: "Resumable: not restarting after interruption.",
      138: "Chunked: transferring large files reliably.",
      139: "High-volume environments.",
      140: "Large file size positioning (claim — verify before publishing).",
      141: "Progress indicators.",
      142: "Parallel uploads for batch efficiency.",
      312: "Architecture view of large-file reliability.",
    },
  },
  {
    id: "processing",
    label: "Processing",
    primary: 143,
    members: [21, 143, 144, 145, 146, 311],
    overlapRisk: "high",
    angles: {
      21: "Indexing outcome of processing (see indexing-metadata).",
      143: "The processing stages: metadata extraction, thumbnails, AI processing.",
      144: "AI queue states: queued, processing, ready.",
      145: "Uploaded versus fully indexed and searchable.",
      146: "Thumbnails for previews without downloading originals.",
      311: "Background processing as a performance design.",
    },
  },
  {
    id: "previews-delivery",
    label: "Previews and delivery",
    primary: 147,
    members: [146, 147, 304, 305, 306, 313, 314],
    overlapRisk: "high",
    angles: {
      146: "Thumbnails as the lightest preview (see processing).",
      147: "In the library: inspecting large media quickly without full downloads.",
      304: "CDN delivery of previews and media.",
      305: "Edge caching of frequently accessed content.",
      306: "Architecture view: how streaming previews are delivered.",
      313: "Preview generation and streaming reducing review friction.",
      314: "Teams across geographical regions.",
    },
  },
  {
    id: "storage-analytics",
    label: "Storage analytics",
    primary: 183,
    members: [148, 149, 183, 192, 209, 357],
    overlapRisk: "high",
    angles: {
      148: "Storage management: how the library is distributed across videos, images, documents and audio.",
      149: "Historical growth of the library.",
      183: "Analytics view: space consumed per asset category.",
      192: "The category breakdown itself (video, image, document, audio).",
      209: "Anticipating storage and operational requirements.",
      357: "Efficiency: understanding consumption and duplicates.",
    },
  },

  /* Permissions & Multi-Tenancy ------------------------------------------------------------ */
  {
    id: "access-control",
    label: "Access control",
    primary: 153,
    members: [151, 152, 153, 154, 155, 156, 157, 158, 169, 175, 176, 178, 295, 325, 337],
    overlapRisk: "high",
    angles: {
      151: "Overview: granular permissions across library areas.",
      152: "Folder-level control finer than organisation-wide access.",
      153: "Roles: owners, administrators, managers, editors, individual users.",
      154: "The access model: new folders private until access is granted.",
      155: "Managers scoped to their folders or teams.",
      156: "Editors without administrative privileges.",
      157: "Targeted individual access where roles are not granular enough.",
      158: "Organisation admins managing policies, users, folders and settings.",
      169: "Enterprise: across departments, projects and folders.",
      175: "Team-based consistency.",
      176: "Departments limited to relevant libraries.",
      178: "Hierarchies: broad roles combined with folder controls.",
      295: "Migration: translating existing access structures.",
      325: "Security angle of RBAC: limiting what users can perform.",
      337: "Security angle of default-deny: new content not automatically exposed.",
    },
  },
  {
    id: "multi-tenancy",
    label: "Multi-tenancy",
    primary: 160,
    members: [72, 84, 160, 161, 162, 163, 164, 165, 166, 167, 168, 177, 215, 276, 324, 372, 387],
    overlapRisk: "high",
    angles: {
      72: "Client review workflows per isolated client (see approvals).",
      84: "Agency collaboration across client libraries (see team-collaboration).",
      160: "Overview: multiple isolated environments, such as agencies with multiple clients.",
      161: "Each client environment logically isolated.",
      162: "Agencies running many client libraries from one platform.",
      163: "Per-client storage allocation and boundaries.",
      164: "Client-specific AI key management.",
      165: "Client-specific authentication options.",
      166: "White-label client-facing experiences.",
      167: "Outcome: unrelated customer libraries never mixed in workflows.",
      215: "Use case: creative agencies managing multiple clients.",
      168: "Agency asset management with structured separation.",
      177: "Client workspaces as the organising unit.",
      276: "API requests carrying tenant context.",
      324: "Security architecture: tenant-scoped data access.",
      372: "Vendor-neutral explainer: what multi-tenant DAM is.",
      387: "FAQ: direct yes answer.",
    },
  },
  {
    id: "access-audit",
    label: "Access history and maps",
    primary: 171,
    members: [170, 171, 173, 197, 198],
    overlapRisk: "high",
    angles: {
      170: "Permission changes recorded in audit history.",
      171: "Important user interactions with the library.",
      173: "Permissions angle: how folders are accessed across teams.",
      197: "Usage angle (see usage-tracking).",
      198: "Analytics angle: which library areas receive attention.",
    },
  },
  {
    id: "secure-collaboration",
    label: "Secure sharing and collaboration",
    primary: 180,
    members: [172, 174, 180],
    overlapRisk: "low",
  },

  /* Analytics ------------------------------------------------------------------------------ */
  {
    id: "library-analytics",
    label: "Library analytics",
    primary: 181,
    members: [181, 184, 185, 186, 191, 193, 194, 196],
    overlapRisk: "high",
    angles: {
      181: "Overview: uploads, comments, storage, contributors, tags and activity.",
      184: "New content entering over time.",
      185: "Who adds content and participates.",
      186: "Frequently used or searched tags and how the library is discovered.",
      191: "The dashboard as a visual overview.",
      193: "What users look for most, as a search-demand signal.",
      194: "Ranking of the most active contributors.",
      196: "Health: growth, duplicates, inactive content.",
    },
  },
  {
    id: "analytics-cadence",
    label: "Daily, weekly and monthly analytics",
    primary: 187,
    members: [187, 188, 189, 190],
    overlapRisk: "medium",
  },
  {
    id: "team-analytics",
    label: "Analytics by team",
    primary: 199,
    members: [195, 199, 200, 201, 202, 203, 210],
    overlapRisk: "medium",
  },
  {
    id: "reporting",
    label: "Reporting and metrics",
    primary: 205,
    members: [205, 206, 207, 208, 209, 210],
    overlapRisk: "high",
    angles: {
      205: "Turning analytics into operational decisions.",
      206: "Quantitative view of activity, storage and collaboration.",
      207: "Which KPIs: uploads, storage, searches, contributors, comments, activity.",
      208: "How assets move through upload, review and approval.",
      209: "Growth reporting for planning.",
      210: "Executive-level view.",
    },
  },

  /* Use cases ------------------------------------------------------------------------------ */
  { id: "uc-video-production", label: "Video and production", primary: 211, members: [211, 212, 216, 217, 218, 229], overlapRisk: "low" },
  { id: "uc-marketing-brand", label: "Marketing, brand and commerce", primary: 213, members: [213, 214, 223, 224, 225, 230, 231, 234], overlapRisk: "medium" },
  { id: "uc-agencies", label: "Agencies and consultancies", primary: 215, members: [162, 168, 202, 215, 219, 221, 229, 346, 354], overlapRisk: "low" },
  { id: "uc-studios-creators", label: "Studios, in-house teams and creators", primary: 220, members: [220, 222, 226, 227, 228], overlapRisk: "low" },
  { id: "uc-communications", label: "Media, communications and organisations", primary: 240, members: [232, 233, 235, 236, 237, 238, 239, 240], overlapRisk: "medium" },

  /* Integrations & Developers -------------------------------------------------------------- */
  { id: "integrations-overview", label: "Integrations", primary: 241, members: [241, 260, 390], overlapRisk: "low" },
  { id: "creative-tool-integrations", label: "Creative tools", primary: 247, members: [247, 248, 249, 250], overlapRisk: "low" },
  { id: "workflow-automation", label: "Automation", primary: 251, members: [246, 251, 257, 278], overlapRisk: "low" },
  {
    id: "api-platform",
    label: "The GetSibu API",
    primary: 261,
    members: [253, 254, 255, 258, 259, 261, 273, 274, 279, 280, 388],
    overlapRisk: "high",
    angles: {
      253: "REST API: the same platform capabilities the interface uses.",
      254: "API-first architecture as positioning: build custom experiences on the asset system.",
      255: "What developers integrate: upload, search, collaboration and other workflows.",
      258: "The playground for testing requests.",
      259: "SDK direction (claim — verify availability before publishing).",
      261: "Overview: programmatic access for developers and technology teams.",
      273: "Documentation as the resource for building integrations.",
      274: "OpenAPI specification for understanding endpoints and generating tooling.",
      279: "Custom applications built on GetSibu asset infrastructure.",
      280: "Section root: DAM integrated into existing software environments.",
      388: "FAQ: direct yes answer.",
    },
  },
  { id: "api-endpoints", label: "API capabilities", primary: 262, members: [262, 263, 264, 265, 266, 267], overlapRisk: "low" },
  {
    id: "webhooks",
    label: "Webhooks and events",
    primary: 268,
    members: [252, 257, 268, 269, 270, 271, 272],
    overlapRisk: "high",
    angles: {
      252: "What webhooks are in GetSibu: notifications to external systems when events occur.",
      257: "Automation: triggering downstream workflows from assets, comments and approvals.",
      268: "The event catalogue: reacting to platform activity.",
      269: "Asset created.",
      270: "Comment added.",
      271: "Approval requested.",
      272: "Billing events.",
    },
  },
  {
    id: "api-security",
    label: "API authentication and security",
    primary: 277,
    members: [256, 275, 276, 277],
    overlapRisk: "high",
    angles: {
      256: "Applications: authenticated access within security boundaries.",
      275: "Developers: supported authentication credentials.",
      276: "Tenant context on API access (see multi-tenancy).",
      277: "Why API security matters for automated access to assets.",
    },
  },

  /* Migration ------------------------------------------------------------------------------ */
  {
    id: "migration-overview",
    label: "Moving to GetSibu",
    primary: 281,
    members: [131, 134, 281, 282, 288, 298, 300, 376],
    overlapRisk: "high",
    angles: {
      131: "Scale: large libraries with metadata and folder relationships preserved.",
      134: "Leaving fragmented storage systems.",
      281: "Section root: from shared drives, cloud storage or other DAM systems.",
      282: "Into a more searchable, structured environment.",
      288: "Preserving valuable context while moving data.",
      298: "The team's transition from fragmented folders.",
      300: "Support and reducing operational disruption.",
      376: "Vendor-neutral explainer: what DAM migration is.",
    },
  },
  { id: "migration-sources", label: "Migration by source", primary: 283, members: [283, 284, 285], overlapRisk: "low" },
  {
    id: "migration-planning",
    label: "Planning and implementation",
    primary: 289,
    members: [289, 290, 292, 295, 296, 297, 299],
    overlapRisk: "high",
    angles: {
      289: "Strategy: understand storage, metadata, permissions and requirements first.",
      290: "Planning: assets, metadata and permissions considered before transfer.",
      292: "Continuing to use existing storage while indexing runs in the background.",
      295: "Permission mapping.",
      296: "Verifying content and metadata transferred correctly.",
      297: "Onboarding: rollout, training, data verification.",
      299: "Implementation: users, folders, permissions, integrations, metadata, workflows.",
    },
  },
  {
    id: "metadata-preservation",
    label: "Metadata preservation",
    primary: 132,
    members: [22, 132, 286, 293],
    overlapRisk: "high",
    angles: {
      22: "Everyday metadata management (see indexing-metadata).",
      132: "Ingestion: which fields are kept when assets are imported.",
      286: "Migration workstream: carrying metadata over from a previous system.",
      293: "Why it matters: information attached to originals must not disappear in the move.",
    },
  },
  {
    id: "folder-mapping",
    label: "Folder mapping",
    primary: 133,
    members: [133, 287, 294],
    overlapRisk: "high",
    angles: {
      133: "Import option: mirror or remap folders as content is ingested.",
      287: "Migrating an existing folder structure as a whole.",
      294: "The decision: keep the existing organisation or design a new one.",
    },
  },

  /* Architecture & Performance ------------------------------------------------------------- */
  {
    id: "architecture-infrastructure",
    label: "Architecture and infrastructure",
    primary: 301,
    members: [301, 302, 303, 308, 315, 316, 317, 318, 319],
    overlapRisk: "medium",
    angles: {
      302: "Infrastructure sized for large collections while keeping search and previews fast.",
      308: "Storage growth supported by the architecture.",
      315: "API layer scaling independently.",
      316: "Stateless design for horizontal scaling and predictable behaviour.",
    },
  },
  {
    id: "performance",
    label: "Performance",
    primary: 320,
    members: [304, 305, 307, 309, 310, 311, 312, 313, 320],
    overlapRisk: "medium",
    angles: {
      309: "Large libraries: chunked I/O, edge caching and indexing.",
      320: "Summary: fast search, previews, scalable storage and efficient uploads combined.",
    },
  },

  /* Security & Compliance ------------------------------------------------------------------ */
  {
    id: "security-foundations",
    label: "Security foundations",
    primary: 321,
    members: [174, 321, 322, 323, 324, 325, 337, 338, 340],
    overlapRisk: "high",
    angles: {
      174: "Controls against unnecessary or unauthorised access.",
      321: "Section root: encryption, authentication, access control, tenant isolation, audit logging.",
      322: "Encryption at rest (claim — verify).",
      323: "Encrypted storage of OAuth credentials, SMTP passwords and API tokens.",
      324: "Tenant-scoped data access as a security guarantee (see multi-tenancy).",
      325: "RBAC as a security control limiting actions (see access-control).",
      337: "Default-deny as protection against automatic exposure (see access-control).",
      338: "Enterprise combination: identity, encryption, permissions, auditability, isolation.",
      340: "Responsible management of valuable creative assets.",
    },
  },
  { id: "identity", label: "Identity and sign-in", primary: 334, members: [165, 334, 335, 336, 389], overlapRisk: "low" },
  { id: "compliance", label: "Compliance", primary: 328, members: [328, 329, 330], overlapRisk: "low" },
  { id: "resilience", label: "Backups and recovery", primary: 331, members: [94, 110, 331, 332, 333], overlapRisk: "low" },

  /* Pricing & Business value --------------------------------------------------------------- */
  { id: "pricing-plans", label: "Plans and pricing", primary: 341, members: [341, 342, 343, 344, 345, 346, 347, 389], overlapRisk: "low" },
  {
    id: "roi",
    label: "Return on investment",
    primary: 359,
    members: [347, 348, 349, 350, 359, 360],
    overlapRisk: "medium",
    angles: {
      347: "Cost considered alongside storage, productivity, collaboration and admin savings.",
      348: "Workflow: searching, recreating files, version confusion.",
      349: "Discovery: time returned to creating.",
      359: "The business case structure.",
    },
  },
  { id: "productivity", label: "Productivity and efficiency", primary: 351, members: [351, 352, 353, 354, 355, 356, 357, 358], overlapRisk: "medium" },

  /* Resources ------------------------------------------------------------------------------ */
  { id: "dam-fundamentals", label: "DAM fundamentals", primary: 361, members: [7, 361, 373, 374, 375, 376], overlapRisk: "low" },
  { id: "ai-explainers", label: "AI explained", primary: 362, members: [362, 363, 364, 365, 366, 367, 368], overlapRisk: "low" },
  { id: "workflow-explainers", label: "Workflow and governance explained", primary: 369, members: [369, 370, 371, 372], overlapRisk: "low" },
  {
    id: "future-of-dam",
    label: "Where DAM is heading",
    primary: 378,
    members: [377, 378, 379, 380, 400],
    overlapRisk: "high",
    angles: {
      377: "How AI changes DAM now: discoverability without manual metadata.",
      378: "Direction of DAM: systems that understand content and automate organisation.",
      379: "Direction of collaboration: feedback, approvals, versions and assets together.",
      380: "AI-powered libraries as knowledge environments.",
      400: "Conversion manifesto: GetSibu's approach where storage is only the beginning.",
    },
  },

  /* Conversion ----------------------------------------------------------------------------- */
  { id: "conversion", label: "Get started", primary: 391, members: [391, 392, 393, 394, 395, 396, 397, 398, 399, 400], overlapRisk: "low" },
];

/** Conversion page per cluster for contextual CTAs; falls back to CATEGORY_CONVERSION. */
export const CATEGORY_CONVERSION: Record<string, number> = {
  home: 391,
  platform: 395,
  "search-discovery": 393,
  ai: 398,
  collaboration: 396,
  "asset-management": 399,
  "storage-ingestion": 392,
  "permissions-multi-tenancy": 395,
  analytics: 397,
  "use-cases": 395,
  integrations: 392,
  developers: 396,
  migration: 392,
  "architecture-performance": 397,
  "security-compliance": 395,
  "pricing-plans": 391,
  "business-value": 396,
  resources: 394,
  faq: 391,
};

export const clusterById = new Map(CLUSTERS.map((c) => [c.id, c]));
