/**
 * Regenerate content/pages/registry.ts from the files in content/pages.
 *
 *   node scripts/build-content-registry.ts
 *
 * Topic pages live at content/pages/<section>/<pdf-number>-<slug>.ts and default-export PageContent.
 * The registry imports every one of them statically (the site bundles it at build time), ordered by
 * PDF number. The validator fails if a content file is not registered, so run this after adding a page.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = "content/pages";
const walk = (dir: string): string[] => readdirSync(dir).flatMap((f) => (statSync(join(dir, f)).isDirectory() ? walk(join(dir, f)) : [join(dir, f)]));

const files = walk(ROOT)
  .filter((file) => file.endsWith(".ts") && !file.endsWith("registry.ts"))
  .map((file) => {
    const path = relative(ROOT, file).split("\\").join("/");
    const name = path.split("/").at(-1)!;
    const number = name === "home.ts" ? 1 : Number(name.split("-")[0]);
    if (!Number.isInteger(number) || number < 1 || number > 400) throw new Error(`${file}: file name must start with the PDF page number`);
    return { path, number };
  })
  .sort((a, b) => a.number - b.number);

const seen = new Set<number>();
for (const f of files) {
  if (seen.has(f.number)) throw new Error(`Two content files for PDF page ${f.number}`);
  seen.add(f.number);
}

const lines = [
  "/**",
  " * Registry of authored page content — generated by scripts/build-content-registry.ts. Do not edit by hand.",
  " * Every file in content/pages must be imported here; the validator fails if a content file exists that is",
  " * not registered.",
  " */",
  'import type { PageContent } from "../../types/content.ts";',
  ...files.map((f) => `import page${f.number} from "./${f.path}";`),
  "",
  `export const AUTHORED_PAGES: PageContent[] = [${files.map((f) => `page${f.number}`).join(", ")}];`,
  "",
];
writeFileSync(join(ROOT, "registry.ts"), lines.join("\n"));
console.log(`Registered ${files.length} authored page(s)`);
