/**
 * Export the inventory for humans.
 *
 *   npm run inventory:export
 *
 *   docs/page-inventory.csv                    every field, one row per PDF page (400 rows)
 *   docs/architecture/03-page-inventory.md     readable master inventory, grouped as in the PDF
 */
import { readFileSync, writeFileSync } from "node:fs";
import { generated } from "./pipeline-env.ts";
import type { Inventory, InventoryPage, RouteMatrixRow } from "../types/content.ts";
import { clusterById } from "../content/architecture/clusters.ts";
import { sectionById } from "../content/architecture/sections.ts";
import { pageTypeById } from "../content/architecture/page-types.ts";

const inventory: Inventory = JSON.parse(readFileSync(generated("inventory.json"), "utf8"));
const routeMatrix: { rows: RouteMatrixRow[] } = JSON.parse(readFileSync(generated("route-matrix.json"), "utf8"));
const byNumber = new Map(inventory.pages.map((p) => [p.number, p]));
const titles = (ns: number[]) => ns.map((n) => `${n} ${byNumber.get(n)!.title}`).join("; ");

/* CSV -------------------------------------------------------------------------------------- */

const columns: Array<[string, (p: InventoryPage) => string | number | boolean]> = [
  ["pdf_page", (p) => p.number],
  ["title", (p) => p.title],
  ["pdf_group", (p) => `${p.pdfGroup.range} ${p.pdfGroup.label}`],
  ["status", (p) => p.status],
  ["merged_into", (p) => p.mergedInto ?? ""],
  ["section", (p) => sectionById.get(p.section)!.label],
  ["category", (p) => p.category],
  ["role", (p) => p.role],
  ["url", (p) => p.path],
  ["aliases", (p) => p.aliases.join(" ")],
  ["parent", (p) => p.parentPath ?? ""],
  ["breadcrumb", (p) => p.breadcrumb.map((b) => b.label).join(" > ")],
  ["page_type", (p) => `${pageTypeById.get(p.pageType)!.letter} ${pageTypeById.get(p.pageType)!.label}`],
  ["recipe", (p) => p.recipe],
  ["primary_topic", (p) => p.primaryTopic],
  ["intent", (p) => p.intent],
  ["purpose", (p) => p.purpose],
  ["key_statement", (p) => p.keyStatement],
  ["angle", (p) => p.angle ?? ""],
  ["clusters", (p) => p.clusters.map((c) => clusterById.get(c)!.label).join("; ")],
  ["related", (p) => titles(p.related)],
  ["mentions", (p) => titles(p.mentions)],
  ["related_features", (p) => titles(p.relatedFeatures)],
  ["related_resources", (p) => titles(p.relatedResources)],
  ["related_faqs", (p) => titles(p.relatedFaqs)],
  ["related_use_cases", (p) => titles(p.relatedUseCases)],
  ["children", (p) => p.children.length],
  ["cta_primary", (p) => `${p.cta.primary.label} -> ${p.cta.primary.href}`],
  ["cta_contextual", (p) => (p.cta.contextual ? `${p.cta.contextual.label} -> ${p.cta.contextual.href}` : "")],
  ["seo_title", (p) => p.seo.title],
  ["meta_description", (p) => p.seo.description],
  ["canonical", (p) => p.seo.canonicalPath],
  ["schema_types", (p) => p.seo.schemaTypes.join(" ")],
  ["robots", (p) => p.seo.robots],
  ["in_sitemap", (p) => p.seo.sitemap],
  ["search_group", (p) => p.searchGroup],
  ["visual_medium", (p) => p.visual.medium.join(" ")],
  ["visual_concept", (p) => p.visual.concept],
  ["claims", (p) => p.claims.join(" ")],
  ["needs_verification", (p) => p.needsVerification],
  ["publication", (p) => p.publication],
  ["context_page", (p) => p.contextPage ?? ""],
  ["source_text", (p) => p.sourceText],
];

const csvCell = (value: string | number | boolean) => {
  const s = String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const csv = [columns.map(([name]) => name).join(","), ...inventory.pages.map((p) => columns.map(([, get]) => csvCell(get(p))).join(","))].join("\n");
// BOM so spreadsheet apps read UTF-8 (em dashes, "×") correctly.
const BOM = String.fromCharCode(0xfeff);
writeFileSync("docs/page-inventory.csv", `${BOM}${csv}\n`);

/* Markdown --------------------------------------------------------------------------------- */

const md: string[] = [];
const canonical = inventory.pages.filter((p) => p.status === "canonical");
md.push("# C. Master Page Inventory");
md.push("");
md.push("> Generated by `npm run inventory:export` from `content/generated/inventory.json`. Do not edit by hand —");
md.push("> change `content/architecture/*` and rebuild. Every column, including source text, is in `docs/page-inventory.csv`.");
md.push("");
md.push(`**${inventory.pages.length} PDF pages → ${canonical.length} canonical URLs + ${inventory.indexes.length} generated hubs + ${inventory.redirects.length} redirects.**`);
md.push("");
md.push("Legend: **Type** = page type letter (see 04-page-types.md). **Publication** = *framed* (the source paragraph states a claim not publishable yet; the page publishes with verified context) or *held* (the title itself states such a claim; not published, the URL redirects temporarily — see 16-launch-readiness.md). **CTA** = contextual conversion page.");
md.push("");

md.push("## Generated hubs (not PDF pages)");
md.push("");
md.push("| URL | H1 | Lede source | Groups |");
md.push("|---|---|---|---|");
for (const i of inventory.indexes) {
  const source = i.ledeSource.map((s) => (s.kind === "pdf" ? `PDF p.${s.page}` : s.kind)).join(", ");
  md.push(`| \`${i.path}\` | ${i.h1} | ${source} | ${i.groups.map((g) => `${g.label} (${g.pages.length})`).join(", ")} |`);
}
md.push("");

md.push("## Redirects");
md.push("");
for (const r of inventory.redirects) md.push(`- \`${r.source}\` → \`${r.destination}\` (308)`);
md.push("");

const groups = [...new Map(inventory.pages.map((p) => [p.pdfGroup.range, p.pdfGroup])).values()];
for (const group of groups) {
  const members = inventory.pages.filter((p) => p.pdfGroup.range === group.range);
  md.push(`## ${group.range} · ${group.label}${group.headingInSource ? "" : " (no heading in PDF)"}`);
  md.push("");
  md.push("| # | Title | URL | Type | Recipe | Clusters | Related | CTA | Publication |");
  md.push("|---|---|---|---|---|---|---|---|---|");
  for (const p of members) {
    const type = pageTypeById.get(p.pageType)!;
    if (p.status === "merged") {
      md.push(`| ${p.number} | ${p.title} | merged into **${p.mergedInto}** → \`${p.path}\` | — | — | — | — | — | — |`);
      continue;
    }
    const url = p.role === "leaf" ? `\`${p.path}\`` : `**\`${p.path}\`**`;
    const clusters = p.clusters.map((c) => clusterById.get(c)!.label).join("; ");
    const cta = p.cta.contextual ? p.cta.contextual.target.replace("page:", "") : "—";
    md.push(`| ${p.number} | ${p.title} | ${url} | ${type.letter} | ${p.recipe} | ${clusters} | ${p.related.join(", ")} | ${cta} | ${p.publication === "held" ? "held" : p.needsVerification ? "framed" : ""} |`);
  }
  md.push("");
}

writeFileSync("docs/architecture/03-page-inventory.md", `${md.join("\n")}\n`);
console.log(`Exported docs/page-inventory.csv (${inventory.pages.length} rows) and docs/architecture/03-page-inventory.md`);

/* Route matrix ---------------------------------------------------------------------------------- */

const matrixColumns: Array<keyof RouteMatrixRow> = ["path", "class", "kind", "pdfPage", "title", "status", "destination", "indexable", "sitemap", "search", "navigation", "claims", "note"];
const matrixCsv = [
  matrixColumns.join(","),
  ...routeMatrix.rows.map((row) => matrixColumns.map((key) => csvCell(Array.isArray(row[key]) ? (row[key] as string[]).join(" ") : (row[key] as string | number | boolean | null) ?? "")).join(",")),
].join("\n");
writeFileSync("docs/route-matrix.csv", `${matrixCsv}\n`);
console.log(`Exported docs/route-matrix.csv (${routeMatrix.rows.length} routes)`);
