/**
 * 374 · What Is Asset Metadata? — /resources/what-is-asset-metadata
 *
 * Angle (cluster: dam-fundamentals; indexing-metadata): vendor-neutral explainer of metadata — its main kinds, where
 * it comes from, the standards (EXIF, IPTC, XMP), embedded, sidecar and system-held metadata, and how it builds up
 * over an asset's life. Creative Asset Indexing (21) owns processing on entry, Media Metadata Management (22) the
 * fields in GetSibu's asset record, Asset Metadata Search (23) searching them, AI Media Indexing (50) AI signals.
 */
import type { PageContent } from "../../../types/content.ts";

const EXPLAINS = { kind: "editorial", note: "Vendor-neutral explanation of asset metadata and its standards; states no GetSibu capability beyond the cited pages." } as const;

const page: PageContent = {
  page: 374,
  lastReviewed: "2026-09-15",
  sections: [
    {
      kind: "hero",
      id: "hero",
      layout: "centered",
      eyebrow: "Resources",
      lede: "What asset metadata is, the kinds an asset carries, what EXIF, IPTC and XMP actually are, why metadata goes missing between systems, and how GetSibu keeps it as part of the asset record.",
      actions: [
        { kind: "global", cta: "primary" },
      ],
      sources: [{ kind: "pdf", page: 374 }, { kind: "pdf", page: 22 }],
    },
    {
      kind: "definition",
      id: "definition",
      eyebrow: "Definition",
      term: "Asset metadata",
      answer: "Asset metadata is information describing a file, including creator, format, dimensions, keywords and other contextual details. It is data about the asset rather than the asset itself.",
      detail: "A photograph’s pixels are its content; the camera model, capture date, photographer, caption, keywords and licence terms are its metadata. Some of that is written into the file automatically, some is added by people and some is generated by software. Together it lets a library answer questions nobody could answer by looking at the image alone.",
      sources: [{ kind: "pdf", page: 374 }, EXPLAINS],
    },
    {
      kind: "overview",
      id: "overview",
      heading: "The information that makes a file findable and usable",
      body: [
        "Metadata is everything a library knows about an asset beyond its content: what it is, where it came from, who made it, how it may be used and how it relates to other assets.",
        "Without metadata, a library can show only files and their names. With it, people can search by creator or campaign, filter by format or date, check whether a licence still applies and understand why an asset exists. Metadata is also fragile. It can be stripped when a file is exported for the web, dropped when files move between systems, or never entered because nobody had the time.",
        [
          "That is why metadata deserves attention at every hand-off, and most of all during a ",
          { text: "DAM migration", page: 376 },
          ". It also works hand in hand with an ",
          { text: "asset taxonomy", page: 375 },
          ", which decides the vocabulary that descriptive fields should use.",
        ],
      ],
      keyPoints: {
        heading: "Key concepts",
        items: ["Data about the asset", "Technical, descriptive and rights information", "Embedded in the file or held by the system", "EXIF, IPTC and XMP", "Easily lost at hand-offs"],
      },
      highlight: {
        heading: "In practice",
        body: "A picture editor looks for every image by one photographer from a previous season. Capture dates came from the camera and the credit from the photographer’s export, so neither had to be typed in by the library team.",
        tags: ["Photography", "Search", "Rights"],
      },
      glance: {
        heading: "Asset metadata in brief",
        facts: [
          { label: "Area", value: "Search and organisation" },
          { label: "Examples", value: "Creator, format, dimensions, keywords" },
          { label: "Common standards", value: "EXIF, IPTC, XMP" },
          { label: "Feature page", value: "Media Metadata Management", page: 22 },
        ],
        actions: [{ kind: "route", path: "/resources", label: "More in Resources" }]
      },
      sources: [{ kind: "pdf", page: 374 }, { kind: "pdf", page: 376 }, { kind: "pdf", page: 375 }, { kind: "pdf", page: 22 }, EXPLAINS],
    },
    {
      kind: "matrix",
      id: "kinds",
      eyebrow: "Kinds of metadata",
      heading: "The main kinds of metadata an asset carries",
      columns: ["Examples", "Usually comes from"],
      rows: [
        { label: "Technical", cells: ["Format, dimensions, duration, file size, colour space", "The file and the device or software that made it"] },
        { label: "Descriptive", cells: ["Title, caption, keywords, subject, campaign", "People, and increasingly AI analysis"] },
        { label: "Administrative", cells: ["Creator, owner, upload date, project, client", "Creative software and the library at upload"] },
        { label: "Rights and usage", cells: ["Copyright holder, licence terms, territories, end date", "Legal, licensing and brand teams"] },
        { label: "Structural", cells: ["Versions, pages, related assets", "The library, as assets are revised and linked"] },
      ],
      sources: [{ kind: "pdf", page: 374 }, EXPLAINS],
    },
    {
      kind: "accordion",
      id: "standards",
      eyebrow: "Key terms",
      heading: "Standards and terms worth knowing",
      items: [
        {
          heading: "EXIF",
          summary: "Technical details that cameras and phones write into image files.",
          icon: "camera",
          body: [
            "EXIF, short for Exchangeable Image File Format, records details at the moment of capture: date and time, camera and lens model, and exposure settings such as aperture and shutter speed. Because the device writes it, EXIF describes how a picture was taken rather than what the picture shows.",
          ],
        },
        {
          heading: "IPTC",
          summary: "A long-established standard for descriptive and rights information on photographs.",
          icon: "news",
          body: [
            "The IPTC Photo Metadata Standard, which originated in news photography, defines fields such as headline, caption, keywords, creator, credit line and copyright notice. It is widely supported by photo software, and its fields are now commonly stored using XMP.",
          ],
        },
        {
          heading: "XMP",
          summary: "An extensible framework for storing metadata in many kinds of file.",
          icon: "code",
          body: [
            "XMP, the Extensible Metadata Platform, is now an international standard. It stores metadata as structured XML and can carry descriptive, rights and workflow information in images, PDFs, video and design files. Because it is extensible, organisations can define fields of their own alongside the standard ones.",
          ],
        },
        {
          heading: "Embedded and sidecar metadata",
          summary: "Metadata can live inside the file or in a companion file beside it.",
          icon: "document",
          body: [
            "Embedded metadata travels inside the file when it is copied, unless software strips it along the way. Some formats, including many camera raw files, are not usually written to, so software keeps XMP in a sidecar file with a matching name. Sidecars are easily separated from their originals, a common cause of lost keywords.",
          ],
        },
        {
          heading: "Metadata held by the library",
          summary: "Much of what a DAM knows is stored in its own records, not in the file.",
          icon: "database",
          body: [
            "Approval status, comments, usage history, permissions and many custom fields exist only in the library’s records. They are not normally written back into the file, so a downloaded copy leaves them behind and a migration has to carry them across on purpose.",
          ],
        },
        {
          heading: "Custom fields",
          summary: "Fields an organisation adds to describe how it works.",
          icon: "tag",
          body: [
            "Campaign codes, product references, markets, channels and agencies are typical examples. They are among the most valuable metadata a library holds, and among the easiest to lose if nobody writes down what each field means.",
          ],
        },
      ],
      sources: [EXPLAINS],
    },
    {
      kind: "workflow",
      id: "builds-up",
      eyebrow: "Over an asset’s life",
      heading: "How metadata accumulates around an asset",
      stages: [
        { label: "Capture", body: "A camera, recorder or scanner writes technical details such as date, device and settings into the file." },
        { label: "Creation", body: "Editing and design software adds or changes fields, and a creator may add a caption, credit or copyright notice on export." },
        { label: "Ingest", body: "The library reads what is embedded, records details such as the file path and upload date, and derives technical information of its own." },
        { label: "Enrichment", body: "People and AI analysis add descriptive keywords, categories and references to campaigns or products." },
        { label: "Use", body: "Approvals, comments, usage and version history build up in the library’s records while the asset is in service." },
      ],
      sources: [EXPLAINS],
    },
    {
      kind: "capabilities",
      id: "in-getsibu",
      eyebrow: "In GetSibu",
      heading: "How GetSibu handles asset metadata",
      items: [
        {
          heading: "Part of the asset record",
          body: "Metadata such as EXIF, XMP, file paths, creators and custom keywords can become part of the asset record, which preserves context.",
          icon: "database",
          page: 22,
        },
        {
          heading: "Processed on entry",
          body: "When assets enter GetSibu, the platform processes available metadata and prepares them for search and organisation, creating an indexed representation of the library.",
          icon: "scan",
          page: 21,
        },
        {
          heading: "Carried through a migration",
          body: "The same kinds of information can be preserved when a library moves, so valuable details attached to original files do not disappear on the way.",
          icon: "upload",
          page: 132,
        },
        {
          heading: "AI signals beside metadata",
          body: "AI media indexing prepares creative content for discovery by processing supported visual, textual and metadata signals.",
          icon: "sparkles",
          page: 50,
        },
        {
          heading: "Available to other systems",
          body: "The API can expose asset information, so external systems can work with metadata programmatically.",
          icon: "api",
          page: 264,
        },
      ],
      sources: [{ kind: "pdf", page: 22 }, { kind: "pdf", page: 21 }, { kind: "pdf", page: 132 }, { kind: "pdf", page: 293 }, { kind: "pdf", page: 50 }, { kind: "pdf", page: 264 }],
    },
    {
      kind: "faq",
      id: "faq",
      heading: "Questions about asset metadata",
      items: [
        {
          question: "What is a metadata schema?",
          answer: "A schema defines which fields a library uses, what each one means and what values it accepts, such as a date format or a fixed list of markets. Agreeing one before content arrives stops the same information being recorded in several different ways.",
        },
        {
          question: "Is a tag the same as asset metadata?",
          answer: "A tag is one kind of descriptive metadata: a keyword attached to an asset to help search and grouping. Metadata is the wider category, which also covers technical details, rights information and relationships between assets.",
        },
        {
          question: "How reliable is embedded metadata?",
          answer: "Useful, but worth checking. Camera clocks are often left on the wrong time zone, files saved from a template can inherit someone else’s credit, and editing software may overwrite fields on export, so dates, credits and rights details deserve a look before anyone relies on them.",
        },
        {
          question: "Can asset metadata be searched in GetSibu?",
          answer: ["Yes. Available metadata can be searched alongside tags and extracted content, and ", { text: "asset metadata search", page: 23 }, " is especially useful when nobody knows a file’s original name or the folder it came from."],
        },
      ],
      sources: [{ kind: "pdf", page: 23 }, EXPLAINS],
    },
    {
      kind: "related",
      id: "related",
      heading: "More on metadata and indexing",
      variant: "compact",
      pages: [22, 23, 21, 50, 132, 375],
      sources: [{ kind: "editorial", note: "Links to pages cited on this page and the taxonomy explainer." }],
    },
    {
      kind: "cta",
      id: "cta",
      heading: "Make Every Asset Discoverable",
      conversionPage: 394,
      surface: "inverse",
      actions: [{ kind: "global", cta: "primary" }],
      sources: [{ kind: "pdf", page: 394 }],
    },
  ],
};

export default page;
